<a href="https://www.kaggle.com/code/anushkaxd/notebook294954fb35?scriptVersionId=352794473" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
/kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source1.tsv

In [2]:
import pandas as pd

base = "/kaggle/input/datasets/anushkxd/000001"

train_ground_truth = pd.read_csv(
    f"{base}/train_ground_truth.tsv",
    sep="\t"
)

train_source1 = pd.read_csv(
    f"{base}/train_source1.tsv",
    sep="\t"
)

train_source2 = pd.read_csv(
    f"{base}/train_source2.tsv",
    sep="\t"
)

train_source3 = pd.read_csv(
    f"{base}/train_source3.tsv",
    sep="\t"
)

print("Ground Truth:", train_ground_truth.shape)
print("Source 1:", train_source1.shape)
print("Source 2:", train_source2.shape)
print("Source 3:", train_source3.shape)

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/anushkxd/000001/train_ground_truth.tsv'

In [3]:
import glob

files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

for file in files:
    print(file)

/kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
/kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source1.tsv

In [4]:
import pandas as pd
import glob

files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

for file in files:
    print("\nFILE:", file)
    df_temp = pd.read_csv(file, sep="\t")
    print("Shape:", df_temp.shape)
    print("Columns:", list(df_temp.columns))

FILE: /kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
Shape: (4887273, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

FILE: /kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
Shape: (5082316, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

FILE: /kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
Shape: (1732544, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

FILE: /kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
Shape: (2206821, 2)
Columns: ['source1_entity_id', 'matched_entity_ids']

FILE: /kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
Shape: (5285603, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

FILE: /kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
Shape: (5034616, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

FILE: /kaggle/input/datasets/anushkaxd/000001/train_source1.tsv
Shape: (2206821, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

In [8]:
import glob

files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

for file in files:
    print(file)

/kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
/kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
/kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
/kaggle/input/datasets/anushkaxd/000001/train_source1.tsv

In [9]:
import pandas as pd

TRAIN_S1 = "/kaggle/input/datasets/anushkxd/000001/train_source1.tsv"
TRAIN_S2 = "/kaggle/input/datasets/anushkxd/000001/train_source2.tsv"
TRAIN_S3 = "/kaggle/input/datasets/anushkxd/000001/train_source3.tsv"

SAMPLE_SIZE = 10000

s1 = pd.read_csv(
    TRAIN_S1,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)

s2 = pd.read_csv(
    TRAIN_S2,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)

s3 = pd.read_csv(
    TRAIN_S3,
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)

print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)

display(s1.head())
display(s2.head())
display(s3.head())

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/anushkxd/000001/train_source1.tsv'

In [20]:
import pandas as pd
import glob
import os

# Find all TSV files automatically
files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

file_paths = {
    os.path.basename(file): file
    for file in files
}

# Load only 10,000 rows for inspection
s1 = pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=10000
)

s2 = pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=10000
)

s3 = pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=10000
)

print("S1 shape:", s1.shape)
print("S2 shape:", s2.shape)
print("S3 shape:", s3.shape)

print("\nS1:")
display(s1.head())

print("\nS2:")
display(s2.head())

print("\nS3:")
display(s3.head())

S1 shape: (10000, 4)
S2 shape: (10000, 4)
S3 shape: (10000, 4)

S1:

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

S2:

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

S3:

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [30]:
import re
import unicodedata


def normalize_text(text):
    if not isinstance(text, str) or text == "":
        return ""

    # Normalize Unicode characters
    text = unicodedata.normalize("NFKC", text)

    # Case normalization
    text = text.casefold()

    # Remove punctuation/symbols, but KEEP:
    # L = letters
    # M = combining marks
    # N = numbers
    cleaned = []

    for char in text:
        category = unicodedata.category(char)

        if category[0] in ("L", "M", "N"):
            cleaned.append(char)
        else:
            cleaned.append(" ")

    text = "".join(cleaned)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# Apply to our samples
for df in [s1, s2, s3]:
    df["business_name_norm"] = df["business_name"].map(normalize_text)
    df["business_address_norm"] = df["business_address"].map(normalize_text)
    df["country_norm"] = df["country"].map(normalize_text)

print("Unicode-safe normalization completed.")

Unicode-safe normalization completed.

In [29]:
print("S1 columns:")
print(s1.columns.tolist())

print("\nS2 columns:")
print(s2.columns.tolist())

print("\nS3 columns:")
print(s3.columns.tolist())

S1 columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_norm', 'business_address_norm', 'country_norm']

S2 columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_norm', 'business_address_norm', 'country_norm']

S3 columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_norm', 'business_address_norm', 'country_norm']

In [31]:
print(s2[[
    "business_name",
    "business_name_norm",
    "business_address",
    "business_address_norm",
    "country",
    "country_norm"
]].head(10).to_string(index=False))

                                                           business_name                                                     business_name_norm                                                           business_address                                                 business_address_norm country country_norm
                                         राम मार्केटिंग प्राइवेट लिमिटेड                                        राम मार्केटिंग प्राइवेट लिमिटेड                               KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi                               kh no 570 13 new delhi west delhi delhi   India        india
                                            -- Holloway Peak Inc Seafood                                              holloway peak inc seafood                                                  105 ELM ST, MORGANTON, NC                                               105 elm st morganton nc      US           us
                                                आदित्य प्रॉपर्टीज एलएलपी                                               आदित्य प्रॉपर्टीज एलएलपी                           G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh                         g 3 571 gulmohar colony bhopal madhya pradesh   India        india
                                                              Summit Inc                                                             summit inc                                      GREENSBORO, NC, 19 1/2 STARDUST TRAIL                                   greensboro nc 19 1 2 stardust trail      US           us
                                            Delta Tetlecommunication Inc                                           delta tetlecommunication inc                                            914 PIERPONT AVE, CLEVELAND, OH                                         914 pierpont ave cleveland oh      US           us
                                                          Lee and Lawson                                                         lee and lawson                                    1702 Pine Avenue, CITY OF MENOMONIE, WI                                 1702 pine avenue city of menomonie wi      US           us
SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com                                 H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab                              h no 204 c road hoshiarpur punjab punjab   India        india
                                              Shree Infracon Private Ltd                                             shree infracon private ltd 63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKHAN COLONY, KOZHIKODE, Kerala 63 2275 7 alhind tower first floor jafferkhan colony kozhikode kerala   India        india
                                            Chavira Platinum Chimera LLC                                           chavira platinum chimera llc                                         282 SAXONY DRIVE, FTT MITCHELL, KY                                      282 saxony drive ftt mitchell ky      US           us
                                FOUNDATION EXCEL AGENCY PRIVATE  LIMITED                                foundation excel agency private limited                   HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, Maharashtra                 hn 753 e 1 bharat nagar 104 1 1 erandwane maharashtra   India        india

In [36]:
import re

LEGAL_SUFFIXES = [
    # Compound forms first
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "public limited",
    "public ltd",
    "holding company",
    "limited liability company",

    # Single legal suffixes
    "company",
    "corporation",
    "incorporated",
    "limited",
    "llp",
    "llc",
    "corp",
    "inc",
    "pvt",
    "ltd",
    "co"
]


def remove_legal_suffix(name):
    if not name:
        return ""

    name = name.strip()

    # Remove repeated legal suffixes
    changed = True

    while changed:
        changed = False

        for suffix in sorted(LEGAL_SUFFIXES, key=len, reverse=True):
            pattern = rf"\s+{re.escape(suffix)}$"

            if re.search(pattern, name):
                name = re.sub(pattern, "", name).strip()
                changed = True
                break

    return name


for df in [s1, s2, s3]:
    df["business_name_core"] = df["business_name_norm"].map(
        remove_legal_suffix
    )

print("Core-name normalization updated.")

Core-name normalization updated.

In [37]:
print(
    s2[
        [
            "business_name",
            "business_name_norm",
            "business_name_core"
        ]
    ].head(20).to_string(index=False)
)

                                                           business_name                                                     business_name_norm                                                     business_name_core
                                         राम मार्केटिंग प्राइवेट लिमिटेड                                        राम मार्केटिंग प्राइवेट लिमिटेड                                        राम मार्केटिंग प्राइवेट लिमिटेड
                                            -- Holloway Peak Inc Seafood                                              holloway peak inc seafood                                              holloway peak inc seafood
                                                आदित्य प्रॉपर्टीज एलएलपी                                               आदित्य प्रॉपर्टीज एलएलपी                                               आदित्य प्रॉपर्टीज एलएलपी
                                                              Summit Inc                                                             summit inc                                                                 summit
                                            Delta Tetlecommunication Inc                                           delta tetlecommunication inc                                               delta tetlecommunication
                                                          Lee and Lawson                                                         lee and lawson                                                         lee and lawson
SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com
                                              Shree Infracon Private Ltd                                             shree infracon private ltd                                                         shree infracon
                                            Chavira Platinum Chimera LLC                                           chavira platinum chimera llc                                               chavira platinum chimera
                                FOUNDATION EXCEL AGENCY PRIVATE  LIMITED                                foundation excel agency private limited                                                foundation excel agency
                                                        heassociates.com                                                       heassociates com                                                       heassociates com
                                        सन कंस्ट्रक्शंस प्राइवेट लिमिटेड                                       सन कंस्ट्रक्शंस प्राइवेट लिमिटेड                                       सन कंस्ट्रक्शंस प्राइवेट लिमिटेड
                              Global Developers Medicals Private Limited                             global developers medicals private limited                                             global developers medicals
                                            ASSET BUILDING COALITION LLC                                           asset building coalition llc                                               asset building coalition
                                       Olszewski Holding Company LLC LLC                                      olszewski holding company llc llc                                                              olszewski
                                                        CANDY'S-SERVICES                                                       candy s services                                                       candy s services
                                                 रियल मॉडर्न फूड लिमिटेड                                                रियल मॉडर्न फूड लिमिटेड                                                रियल मॉडर्न फूड लिमिटेड
                                            Crestline Crestline Clean LP                                           crestline crestline clean lp                                           crestline crestline clean lp
                                                                    Nion                                                                   nion                                                                   nion
                                            Keystone Odyssey Odyssey LLC                                           keystone odyssey odyssey llc                                               keystone odyssey odyssey

In [38]:
import pandas as pd
import glob
import os

file_paths = {
    os.path.basename(file): file
    for file in glob.glob("/kaggle/input/**/*.tsv", recursive=True)
}

ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=20
)

print("Shape:", ground_truth.shape)
print("Columns:", ground_truth.columns.tolist())

display(ground_truth)

Shape: (20, 2)
Columns: ['source1_entity_id', 'matched_entity_ids']

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751             S2-790675320,S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041

In [39]:
# Get the S1 IDs from our ground truth sample
s1_ids = ground_truth["source1_entity_id"].tolist()

print("S1 IDs from ground truth:")
print(s1_ids)

S1 IDs from ground truth:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573', 'S1-730934468', 'S1-7293388', 'S1-546142636', 'S1-274126313', 'S1-145361722', 'S1-503957000', 'S1-692000596', 'S1-561341312', 'S1-777597828', 'S1-282467635']

In [40]:
# Search the full S1 file in chunks for these 20 entities

target_ids = set(s1_ids)
matches = []

for chunk in pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100_000
):
    found = chunk[chunk["entity_id"].isin(target_ids)]

    if len(found) > 0:
        matches.append(found)

    if len(pd.concat(matches)) >= len(target_ids):
        break

s1_gt = pd.concat(matches, ignore_index=True)

print("Found:", len(s1_gt), "of", len(target_ids), "S1 entities")

display(s1_gt)

ValueError: No objects to concatenate

In [41]:
# Find the 20 S1 records from the full training file

target_ids = set(s1_ids)
matches = []

for chunk in pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100_000
):
    found = chunk[chunk["entity_id"].isin(target_ids)]

    if not found.empty:
        matches.append(found)

# Combine only after the scan is complete
if matches:
    s1_gt = pd.concat(matches, ignore_index=True)
else:
    s1_gt = pd.DataFrame()

print("Found:", len(s1_gt), "of", len(target_ids), "S1 entities")

display(s1_gt)

Found: 20 of 20 S1 entities

,entity_id,business_name,business_address,country
0,S1-274126313,"Obsidian, LLC","3907 Hamilton Road, Deer Park, WA",US
1,S1-102811957,Payne Enterprises,"3315 Fremont Street, Peoria, IL",US
2,S1-343815751,Dahlia Power Reliable Scientific LLC,"630 45th Terrace, Kansas City, MO",US
3,S1-777597828,Uptown Pub,"6114 10th Avenue, Spokane Valley, WA",US
4,S1-318373630,Red Ventures Private Limited,"Rajasthan, Jaipur, Banipark, Gokul Apartment, ...",India
5,S1-7293388,Chordia & Partners,"Faridabad, 1038 Sector 9, Haryana",India
6,S1-86989137,Laxmi Golden Investments Private Limited,"New Bridge Business Centre'S 11Th Floor, N1 Bl...",India
7,S1-145361722,Dick Regional Armada Corp,"33466 Warwick Hills Road, Yucaipa, CA",US
8,S1-730934468,Orellana Investments LLC,"728 A Quail Avenue, Fl Ground Floor, Geneva, IA",US
9,S1-656753428,Ss Food Private Limited,"Af-684, Nandgram Near Mother India Public Scho...",India
10,S1-282467635,Prem & Sons Pvt Ltd,"D-4, Chandana Apartments82, Infantry Road, Ban...",India
11,S1-546142636,Crystal Staffing Solutions LLC,"8706 Kentucky Derby Drive, Waxhaw, NC",US
12,S1-503957000,AP Hospitality Inc,"20085 Us 23, Circleville, OH",US
13,S1-29845983,Hendricks and Flowers Inc,"33 Sleepy Hollow Drive, Danbury, CT",US
14,S1-789009573,Hotel Enterprises Limited,"Wz-187C Shop No.13, 14 Kh. No.47 S/F. Vikaspur...",India
15,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
16,S1-692000596,"Desai, Alanah, Esq., PC","584 Summer Street, Unit 1441, Holyoke, MA",US
17,S1-55344266,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
18,S1-561341312,Balaji Investment Private Limited,"Plot No. D-88 & D-90, Hyd, Telangana, Hyderaba...",India
19,S1-18727616,Lumay Boral,"1056 Belden Avenue, Akron, OH",US

In [42]:
# Get all matched S2/S3 entity IDs from our 20 ground-truth rows

matched_ids = set()

for value in ground_truth["matched_entity_ids"]:
    for entity_id in value.split(","):
        entity_id = entity_id.strip()
        if entity_id:
            matched_ids.add(entity_id)

print("Total matched S2/S3 IDs:", len(matched_ids))

# Show a few examples
print("Examples:")
print(list(matched_ids)[:20])

Total matched S2/S3 IDs: 70
Examples:
['S2-680265918', 'S2-681193310', 'S3-555791452', 'S2-249013014', 'S2-836452886', 'S3-858763214', 'S2-994658326', 'S2-625774905', 'S2-153058913', 'S2-478959098', 'S3-641489370', 'S2-120366543', 'S3-576451439', 'S3-775321672', 'S3-11291185', 'S2-383871912', 'S2-24659151', 'S3-74481402', 'S3-523120965', 'S2-483615364']

In [43]:
# Separate S2 and S3 IDs

s2_target_ids = {
    x for x in matched_ids
    if x.startswith("S2-")
}

s3_target_ids = {
    x for x in matched_ids
    if x.startswith("S3-")
}

print("S2 IDs:", len(s2_target_ids))
print("S3 IDs:", len(s3_target_ids))

S2 IDs: 35
S3 IDs: 35

In [44]:
# Retrieve the 35 matched S2 records

s2_matches = []

for chunk in pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100_000
):
    found = chunk[chunk["entity_id"].isin(s2_target_ids)]

    if not found.empty:
        s2_matches.append(found)

s2_gt = pd.concat(s2_matches, ignore_index=True)

print("S2 records found:", len(s2_gt))
display(s2_gt)

S2 records found: 35

,entity_id,business_name,business_address,country
0,S2-648035184,Hendricks and Flowers Inc,"CT, SLEEPY HOLLOW DRIVE, DANBURY",US
1,S2-755677256,Lumay Boral Inc.,"1056-1060 BELDEN AVE, PO BOX 8807, AKRON, OH",US
2,S2-625774905,PAYNE-ENRTPRMISES,"3315 FREMONT SAINT, PEORIA, IL",US
3,S2-383871912,होटल एंटरप्राइजेज लिमिटेड,"WZ-187C SHOP NO.13, DELHI, WEST DELHI, Delhi",India
4,S2-7028416,Chordia & Partners Company,"हरियाणा, 1038 SECTOR 9, FARIDABAD",India
5,S2-939389287,Dick Regional Armada,"33466 WARWICK HILLS ROAD, <NULL>, YUCAIPA, CA",US
6,S2-478959098,Payne Énterprises,"3315 FREMONT ST, PEORIA, IL",US
7,S2-660036492,रेड वेंचर्स प्राइवेट लिमिटेड,"G-1, BANIPARK, JAIPUR, Rajasthan",India
8,S2-157073701,Chordia &-Pártners Ltd,"H.NO 1038 SECTOR 9, FARIABAD, Haryana",India
9,S2-173295926,AP Ínc Center,"20085 US 23, CIRCLEVILLE, OH",US
10,S2-681193310,Maure Wilblims Colombier Inc,,US
11,S2-353308450,AP Inc Hospitality,"20085 US 23, CIRCLEVILLE, OH",US
12,S2-553508714,Payne Enterpires,"3315 FREMONT ST, PEORIA, IL",US
13,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
14,S2-479876582,Dahlia Power Reliable Scientific,"45ND TERRACE, null, KANSAS CITY, MO",US
15,S2-743505751,Maure Williams Colombier,,US
16,S2-580419223,"DESAI, ALANAH,-ESQ.,","SUMMER STREET, HOLLYOKE, MA",US
17,S2-153058913,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCH...",India
18,S2-487600131,Crystal Solutions LLC Partners,"8706 KENTUCKY DERBY DR, WAXHAW, NC",US
19,S2-120366543,Dick Regional,,US
20,S2-680265918,"obsidian, llc",,US
21,S2-790675320,Dahlia Power Reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",US
22,S2-483615364,బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్,"H.NO 00516 PLOT NO. D-88 & D-90, JEEDIMETLA, H...",India
23,S2-582477216,CRYSTAL STAFFING SOLUTIONS-L.L.C.,"8706 KENTUCKY DERBY DR, WAXHAW, NC",US
24,S2-356983532,Orellana Investments Investments Llc,,US
25,S2-938895481,Prem & Pvt Ltd Services,"D-4, CHANDANA APARTMENTS82, INFANTRY ROAD, Kar...",India
26,S2-736616474,"Obsidian,-LLC","3907 HAMILTON RD, DEER PARK CIYT, WA",US
27,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
28,S2-235117490,AP Hospitality Ínc,"20085 US 23, CIRCLEVILLE, OH",US
29,S2-994658326,AP INC SERVICE #80430,"20085 US 23, CIRCLEVILLE, OH",US
30,S2-51486805,"Obsidian, LLC Center","3907 HAMILTON RD, DEER PARK CIYT, WA",US
31,S2-442723188,Chordia + Pagnters - 7306204978,"हरियाणा, DOOR NO 1038 SECTOR 9, FARIDABAD",India
32,S2-836452886,UPTOWN PUB CO,"6114 10RD AVENUE, SPOKANE VALLEY, WA",US
33,S2-392804085,LLC Crystal Sttfrifng Solutions,"8706 KENTUCKY DERBY DRIVE, WAXHAW, NC",US
34,S2-24659151,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, Uttar Pradesh, GHAZIABAD, 9487203",India

In [45]:
# Retrieve the 35 matched S3 records

s3_matches = []

for chunk in pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100_000
):
    found = chunk[chunk["entity_id"].isin(s3_target_ids)]

    if not found.empty:
        s3_matches.append(found)

s3_gt = pd.concat(s3_matches, ignore_index=True)

print("S3 records found:", len(s3_gt))
display(s3_gt)

S3 records found: 35

,entity_id,business_name,business_address,country
0,S3-860443364,Maure Williams Inc Center,,US
1,S3-352439310,LLC Orellana Invsmbens,"728 A Quail Avenue, Fl. Ground Floor, Geneva, ...",US
2,S3-312496301,Laxmi Golden Investments,"New Bridge Buisness Centre's 11Th Floor, N1 Bl...",India
3,S3-641489370,Lumay Boral,"1056c Belden Ave, AKON, Ohio",US
4,S3-449308785,Payne Enterprises LLC,"Fremont St, Peoria, Illinois",US
5,S3-413669121,Solkeloquo,"6114 Tenth Ave, Spokane Valley, Washington",US
6,S3-555791452,AP AP Hospitality Incorporated,"20085-20089 Us 23, Circleville, Ohio",US
7,S3-925631694,"Obsidian, Llc","Deer Park, Washington, Hamilton Rd",US
8,S3-461175723,"Obsidian, [[LLC]]",,US
9,S3-384364074,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India
10,S3-728090388,Payne Etrepndiels,"3315 Fremont St, Peoria, Illinois",US
11,S3-804600254,Red Ventures Private,"Doro No 316 G-1, Gokul Apartment, E-3a Kanti C...",India
12,S3-274817120,Laxmi Gbn lnvestments Private Limited,"New Bridge Bssiness Centre's 11Th Floor, N1 Bl...",India
13,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
14,S3-478195123,Raj Investments எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India
15,S3-33665521,AP Hospitality Inc,"20085-20089 Us 23, Circleville, Ohio",US
16,S3-138350041,Prem & Pvt Ltd Partners,"D-4, Bangalore, KA",India
17,S3-850112871,"Korbrixx D.B.A. Obsidian, LLC","3907 Hamilton Road, Deer Park, WA",US
18,S3-187831601,Lumay Bóral,"1056c Belden Ave, AKON, Ohio",US
19,S3-729771680,LLC Crystal Shaffing Solutions,"870 Kentucky Derby Drive, Waxhaw, North Carolina",US
20,S3-74481402,Hotel Limited Services,"Block B-517 Wz-187c Shop No.13, Divreportingci...",India
21,S3-588502663,Hendricks and Inc Flowers,,US
22,S3-249331830,Crystal,"8706 Kentucky Derby Drive, Waxhaw, NC",US
23,S3-619529814,Balaji Insvstemnt Private Limited,"Plot No. D-88 & D-90, Hyd, Shapurnagar, TG",India
24,S3-164220452,"Desai, Alanah, Ésq.,","584 Summer Street, Holyoke, Massachusetts",US
25,S3-576451439,Hotel Énterprises Limited,"Block B-517 Wz-187c Shop No.13, South West Del...",India
26,S3-928796641,Payne Énterprises,"3315 Fremont Street, Peoria, Illinois",US
27,S3-679606215,एसएस फूड प्राइवेट लिमिटेड,"Af-684, Ghaziabad, UP",India
28,S3-858763214,[Inc] AP Hospitality,"20085-20089 Us 23, Circleville, Ohio",US
29,S3-96572514,[Corp] Dick Regional Armada,"Yucaipa, California, 33466 Warwik Hills Road",US
30,S3-878454467,Dahlia Ponr Reliable Scientific LLC,"Missouri, 630 45th Terrace, Kansas City",US
31,S3-476250621,Lumay Bóral,"1056c Belden Avenue, AKON, Ohio",US
32,S3-523120965,Smt Chordia & Center,"#1038 Sector 9, Faridabad, हरियाणा",India
33,S3-200008747,Llc Crystal Staffing Solutions,"870 Kentucky Derby Drive, Waxhaw, North Carolina",US
34,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [46]:
# Apply our current normalization to the known matched records

for df in [s1_gt, s2_gt, s3_gt]:
    df["business_name_norm"] = df["business_name"].map(normalize_text)
    df["business_address_norm"] = df["business_address"].map(normalize_text)
    df["country_norm"] = df["country"].map(normalize_text)
    df["business_name_core"] = df["business_name_norm"].map(
        remove_legal_suffix
    )

print("Normalization applied to ground-truth records.")

Normalization applied to ground-truth records.

In [47]:
# Show the S2 records after normalization

display(
    s2_gt[
        [
            "entity_id",
            "business_name",
            "business_name_norm",
            "business_name_core",
            "business_address",
            "business_address_norm"
        ]
    ]
)

,entity_id,business_name,business_name_norm,business_name_core,business_address,business_address_norm
0,S2-648035184,Hendricks and Flowers Inc,hendricks and flowers inc,hendricks and flowers,"CT, SLEEPY HOLLOW DRIVE, DANBURY",ct sleepy hollow drive danbury
1,S2-755677256,Lumay Boral Inc.,lumay boral inc,lumay boral,"1056-1060 BELDEN AVE, PO BOX 8807, AKRON, OH",1056 1060 belden ave po box 8807 akron oh
2,S2-625774905,PAYNE-ENRTPRMISES,payne enrtprmises,payne enrtprmises,"3315 FREMONT SAINT, PEORIA, IL",3315 fremont saint peoria il
3,S2-383871912,होटल एंटरप्राइजेज लिमिटेड,होटल एंटरप्राइजेज लिमिटेड,होटल एंटरप्राइजेज लिमिटेड,"WZ-187C SHOP NO.13, DELHI, WEST DELHI, Delhi",wz 187c shop no 13 delhi west delhi delhi
4,S2-7028416,Chordia & Partners Company,chordia partners company,chordia partners,"हरियाणा, 1038 SECTOR 9, FARIDABAD",हरियाणा 1038 sector 9 faridabad
5,S2-939389287,Dick Regional Armada,dick regional armada,dick regional armada,"33466 WARWICK HILLS ROAD, <NULL>, YUCAIPA, CA",33466 warwick hills road null yucaipa ca
6,S2-478959098,Payne Énterprises,payne énterprises,payne énterprises,"3315 FREMONT ST, PEORIA, IL",3315 fremont st peoria il
7,S2-660036492,रेड वेंचर्स प्राइवेट लिमिटेड,रेड वेंचर्स प्राइवेट लिमिटेड,रेड वेंचर्स प्राइवेट लिमिटेड,"G-1, BANIPARK, JAIPUR, Rajasthan",g 1 banipark jaipur rajasthan
8,S2-157073701,Chordia &-Pártners Ltd,chordia pártners ltd,chordia pártners,"H.NO 1038 SECTOR 9, FARIABAD, Haryana",h no 1038 sector 9 fariabad haryana
9,S2-173295926,AP Ínc Center,ap ínc center,ap ínc center,"20085 US 23, CIRCLEVILLE, OH",20085 us 23 circleville oh
10,S2-681193310,Maure Wilblims Colombier Inc,maure wilblims colombier inc,maure wilblims colombier,,
11,S2-353308450,AP Inc Hospitality,ap inc hospitality,ap inc hospitality,"20085 US 23, CIRCLEVILLE, OH",20085 us 23 circleville oh
12,S2-553508714,Payne Enterpires,payne enterpires,payne enterpires,"3315 FREMONT ST, PEORIA, IL",3315 fremont st peoria il
13,S2-197070651,Raj Investments LLP,raj investments llp,raj investments,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",6 29 c i t colony 2nd main road mylapore chenn...
14,S2-479876582,Dahlia Power Reliable Scientific,dahlia power reliable scientific,dahlia power reliable scientific,"45ND TERRACE, null, KANSAS CITY, MO",45nd terrace null kansas city mo
15,S2-743505751,Maure Williams Colombier,maure williams colombier,maure williams colombier,,
16,S2-580419223,"DESAI, ALANAH,-ESQ.,",desai alanah esq,desai alanah esq,"SUMMER STREET, HOLLYOKE, MA",summer street hollyoke ma
17,S2-153058913,एसएस फूड प्राइवेट लिमिटेड,एसएस फूड प्राइवेट लिमिटेड,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCH...",af 0684 nandgram near mother india public scho...
18,S2-487600131,Crystal Solutions LLC Partners,crystal solutions llc partners,crystal solutions llc partners,"8706 KENTUCKY DERBY DR, WAXHAW, NC",8706 kentucky derby dr waxhaw nc
19,S2-120366543,Dick Regional,dick regional,dick regional,,
20,S2-680265918,"obsidian, llc",obsidian llc,obsidian,,
21,S2-790675320,Dahlia Power Reliable,dahlia power reliable,dahlia power reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",kansas city mo 630 45nd terrace null
22,S2-483615364,బాలాజీ ఇన్వెస్ట్‌మెంట్ ప్రైవేట్ లిమిటెడ్,బాలాజీ ఇన్వెస్ట్ మెంట్ ప్రైవేట్ లిమిటెడ్,బాలాజీ ఇన్వెస్ట్ మెంట్ ప్రైవేట్ లిమిటెడ్,"H.NO 00516 PLOT NO. D-88 & D-90, JEEDIMETLA, H...",h no 00516 plot no d 88 d 90 jeedimetla hyd hy...
23,S2-582477216,CRYSTAL STAFFING SOLUTIONS-L.L.C.,crystal staffing solutions l l c,crystal staffing solutions l l c,"8706 KENTUCKY DERBY DR, WAXHAW, NC",8706 kentucky derby dr waxhaw nc
24,S2-356983532,Orellana Investments Investments Llc,orellana investments investments llc,orellana investments investments,,
25,S2-938895481,Prem & Pvt Ltd Services,prem pvt ltd services,prem pvt ltd services,"D-4, CHANDANA APARTMENTS82, INFANTRY ROAD, Kar...",d 4 chandana apartments82 infantry road karnataka
26,S2-736616474,"Obsidian,-LLC",obsidian llc,obsidian,"3907 HAMILTON RD, DEER PARK CIYT, WA",3907 hamilton rd deer park ciyt wa
27,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",6 29 c i t colony 2nd main road mylapore chenn...
28,S2-235117490,AP Hospitality Ínc,ap hospitality ínc,ap hospitality ínc,"20085 US 23, CIRCLEVILLE, OH",20085 us 23 circleville oh
29,S2-994658326,AP INC SERVICE #80430,ap inc service 80430,ap inc service 80430,"20085 US 23, CIRCLEVILLE, OH",20085 us 23 circleville oh
30,S2-51486805,"Obsidian, LLC Center",obsidian llc center,obsidian llc center,"3907 HAMILTON RD, DEER PARK CIYT, WA",3907 hamilton rd deer park ciyt wa
31,S2-442723188,Chordia + Pagnters - 7306204978,chordia pagnters 7306204978,chordia pagnters 7306204978,"हरियाणा, DOOR NO 1038 SECTOR 9, FARIDABAD",हरियाणा door no 1038 sector 9 faridabad
32,S2-836452886,UPTOWN PUB CO,uptown pub co,uptown pub,"6114 10RD AVENUE, SPOKANE VALLEY, WA",6114 10rd avenue spokane valley wa
33,S2-392804085,LLC Crystal Sttfrifng Solutions,llc crystal sttfrifng solutions,llc crystal sttfrifng solutions,"8706 KENTUCKY DERBY DRIVE, WAXHAW, NC",8706 kentucky derby drive waxhaw nc
34,S2-24659151,एसएस फूड प्राइवेट लिमिटेड,एसएस फूड प्राइवेट लिमिटेड,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, Uttar Pradesh, GHAZIABAD, 9487203",af 0684 uttar pradesh ghaziabad 9487203

In [49]:
from difflib import SequenceMatcher


def similarity(a, b):
    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


# Create lookup dictionary for S1 records
s1_lookup = s1_gt.set_index("entity_id").to_dict("index")

rows = []

for _, row in ground_truth.iterrows():

    s1_id = row["source1_entity_id"]

    if s1_id not in s1_lookup:
        continue

    s1_record = s1_lookup[s1_id]

    for matched_id in row["matched_entity_ids"].split(","):

        matched_id = matched_id.strip()

        if matched_id.startswith("S2-"):
            source_df = s2_gt

        elif matched_id.startswith("S3-"):
            source_df = s3_gt

        else:
            continue

        matched = source_df[
            source_df["entity_id"] == matched_id
        ]

        if matched.empty:
            continue

        matched = matched.iloc[0]

        rows.append({
            "s1_id": s1_id,
            "matched_id": matched_id,

            "s1_name": s1_record["business_name_norm"],
            "matched_name": matched["business_name_norm"],

            "name_similarity": similarity(
                s1_record["business_name_norm"],
                matched["business_name_norm"]
            ),

            "s1_core": s1_record["business_name_core"],
            "matched_core": matched["business_name_core"],

            "core_similarity": similarity(
                s1_record["business_name_core"],
                matched["business_name_core"]
            ),

            "s1_address": s1_record["business_address_norm"],
            "matched_address": matched["business_address_norm"],

            "address_similarity": similarity(
                s1_record["business_address_norm"],
                matched["business_address_norm"]
            ),

            "country_match": (
                s1_record["country_norm"]
                == matched["country_norm"]
            )
        })


comparison = pd.DataFrame(rows)

print("Matched pairs evaluated:", len(comparison))

display(comparison.head(20))

Matched pairs evaluated: 70

,s1_id,matched_id,s1_name,matched_name,name_similarity,s1_core,matched_core,core_similarity,s1_address,matched_address,address_similarity,country_match
0,S1-965667,S2-681193310,maure williams colombier inc,maure wilblims colombier inc,0.964286,maure williams colombier,maure wilblims colombier,0.958333,85 wayne avenue ticonderoga ny,,0.000000,True
1,S1-965667,S2-743505751,maure williams colombier inc,maure williams colombier,0.923077,maure williams colombier,maure williams colombier,1.000000,85 wayne avenue ticonderoga ny,,0.000000,True
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,0.171429,maure williams colombier,dréxkor,0.193548,85 wayne avenue ticonderoga ny,85 wanye avenue ticonderoga townshiip new york,0.763158,True
3,S1-965667,S3-11291185,maure williams colombier inc,maurewilliamscolombier com,0.888889,maure williams colombier,maurewilliamscolombier com,0.880000,85 wayne avenue ticonderoga ny,wayne ave ticonderoga townshiip new york,0.685714,True
4,S1-965667,S3-860443364,maure williams colombier inc,maure williams inc center,0.679245,maure williams colombier,maure williams inc center,0.734694,85 wayne avenue ticonderoga ny,,0.000000,True
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,raj investments,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.043478,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,1.000000,True
6,S1-55344266,S2-197070651,raj investments llp,raj investments llp,1.000000,raj investments,raj investments,1.000000,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,1.000000,True
7,S1-55344266,S3-478195123,raj investments llp,raj investments எல்எல்பி,0.744186,raj investments,raj investments எல்எல்பி,0.769231,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,0.927273,True
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,raj investments,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.043478,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,0.837607,True
9,S1-343815751,S2-790675320,dahlia power reliable scientific llc,dahlia power reliable,0.736842,dahlia power reliable scientific,dahlia power reliable,0.792453,630 45th terrace kansas city mo,kansas city mo 630 45nd terrace null,0.417910,True
10,S1-343815751,S2-479876582,dahlia power reliable scientific llc,dahlia power reliable scientific,0.941176,dahlia power reliable scientific,dahlia power reliable scientific,1.000000,630 45th terrace kansas city mo,45nd terrace null kansas city mo,0.793651,True
11,S1-343815751,S3-878454467,dahlia power reliable scientific llc,dahlia ponr reliable scientific llc,0.957746,dahlia power reliable scientific,dahlia ponr reliable scientific,0.952381,630 45th terrace kansas city mo,missouri 630 45th terrace kansas city,0.823529,True
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,ss food,एसएस फूड प्राइवेट लिमिटेड,0.062500,af 684 nandgram near mother india public schoo...,af 0684 nandgram near mother india public scho...,0.767442,True
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,ss food,एसएस फूड प्राइवेट लिमिटेड,0.062500,af 684 nandgram near mother india public schoo...,af 0684 uttar pradesh ghaziabad 9487203,0.320000,True
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,ss food,एसएस फूड प्राइवेट लिमिटेड,0.062500,af 684 nandgram near mother india public schoo...,af 684 ghaziabad up,0.361905,True
15,S1-102811957,S2-478959098,payne enterprises,payne énterprises,0.941176,payne enterprises,payne énterprises,0.941176,3315 fremont street peoria il,3315 fremont st peoria il,0.925926,True
16,S1-102811957,S2-553508714,payne enterprises,payne enterpires,0.909091,payne enterprises,payne enterpires,0.909091,3315 fremont street peoria il,3315 fremont st peoria il,0.925926,True
17,S1-102811957,S2-625774905,payne enterprises,payne enrtprmises,0.882353,payne enterprises,payne enrtprmises,0.882353,3315 fremont street peoria il,3315 fremont saint peoria il,0.877193,True
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,0.588235,payne enterprises,payne etrepndiels,0.588235,3315 fremont street peoria il,3315 fremont st peoria illinois,0.833333,True
19,S1-102811957,S3-928796641,payne enterprises,payne énterprises,0.941176,payne enterprises,payne énterprises,0.941176,3315 fremont street peoria il,3315 fremont street peoria illinois,0.906250,True

In [50]:
print("Name similarity:")
print(comparison["name_similarity"].describe())

print("\nCore-name similarity:")
print(comparison["core_similarity"].describe())

print("\nAddress similarity:")
print(comparison["address_similarity"].describe())

print("\nCountry match:")
print(comparison["country_match"].value_counts())

Name similarity:
count    70.000000
mean      0.716803
std       0.289390
min       0.080000
25%       0.635449
50%       0.816667
75%       0.920879
max       1.000000
Name: name_similarity, dtype: float64

Core-name similarity:
count    70.000000
mean      0.725876
std       0.318428
min       0.035088
25%       0.589325
50%       0.877500
75%       0.949580
max       1.000000
Name: core_similarity, dtype: float64

Address similarity:
count    70.000000
mean      0.694060
std       0.310952
min       0.000000
25%       0.566995
50%       0.828431
75%       0.925926
max       1.000000
Name: address_similarity, dtype: float64

Country match:
country_match
True    70
Name: count, dtype: int64

In [51]:
display(
    comparison.sort_values(
        "name_similarity"
    )[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "name_similarity",
            "core_similarity",
            "address_similarity",
            "country_match"
        ]
    ].head(15)
)

,s1_id,matched_id,s1_name,matched_name,name_similarity,core_similarity,address_similarity,country_match
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,0.043478,1.000000,True
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,0.043478,0.837607,True
31,S1-789009573,S2-383871912,hotel enterprises limited,होटल एंटरप्राइजेज लिमिटेड,0.080000,0.047619,0.565517,True
64,S1-561341312,S2-483615364,balaji investment private limited,బాలాజీ ఇన్వెస్ట్ మెంట్ ప్రైవేట్ లిమిటెడ్,0.082192,0.035088,0.539130,True
25,S1-318373630,S2-660036492,red ventures private limited,रेड वेंचर्स प्राइवेट लिमिटेड,0.107143,0.050000,0.387755,True
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.062500,0.767442,True
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.062500,0.361905,True
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.062500,0.320000,True
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,0.171429,0.193548,0.763158,True
67,S1-777597828,S3-413669121,uptown pub,solkeloquo,0.200000,0.200000,0.783784,True
55,S1-503957000,S2-994658326,ap hospitality inc,ap inc service 80430,0.315789,0.294118,1.000000,True
58,S1-503957000,S2-173295926,ap hospitality inc,ap ínc center,0.322581,0.296296,1.000000,True
45,S1-546142636,S3-249331830,crystal staffing solutions llc,crystal,0.378378,0.424242,1.000000,True
32,S1-789009573,S3-74481402,hotel enterprises limited,hotel limited services,0.553191,0.564103,0.491018,True
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,0.588235,0.588235,0.833333,True

In [52]:
!pip install rapidfuzz -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 36.9 MB/s eta 0:00:0000:0100:01

In [53]:
from rapidfuzz import fuzz

print("RapidFuzz is working!")
print(fuzz.ratio("payne enterprises", "payne enterpires"))

RapidFuzz is working!
90.9090909090909

In [54]:
from rapidfuzz import fuzz

def rapidfuzz_features(a, b):
    return {
        "ratio": fuzz.ratio(a, b) / 100,
        "partial_ratio": fuzz.partial_ratio(a, b) / 100,
        "token_sort_ratio": fuzz.token_sort_ratio(a, b) / 100,
        "token_set_ratio": fuzz.token_set_ratio(a, b) / 100,
        "WRatio": fuzz.WRatio(a, b) / 100
    }

# Apply to the 70 known-correct S1-S2/S3 pairs
comparison["rf_ratio"] = comparison.apply(
    lambda x: fuzz.ratio(x["s1_name"], x["matched_name"]) / 100,
    axis=1
)

comparison["rf_partial"] = comparison.apply(
    lambda x: fuzz.partial_ratio(x["s1_name"], x["matched_name"]) / 100,
    axis=1
)

comparison["rf_token_sort"] = comparison.apply(
    lambda x: fuzz.token_sort_ratio(x["s1_name"], x["matched_name"]) / 100,
    axis=1
)

comparison["rf_token_set"] = comparison.apply(
    lambda x: fuzz.token_set_ratio(x["s1_name"], x["matched_name"]) / 100,
    axis=1
)

comparison["rf_wratio"] = comparison.apply(
    lambda x: fuzz.WRatio(x["s1_name"], x["matched_name"]) / 100,
    axis=1
)

display(
    comparison[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "rf_ratio",
            "rf_partial",
            "rf_token_sort",
            "rf_token_set",
            "rf_wratio"
        ]
    ].head(20)
)

,s1_id,matched_id,s1_name,matched_name,rf_ratio,rf_partial,rf_token_sort,rf_token_set,rf_wratio
0,S1-965667,S2-681193310,maure williams colombier inc,maure wilblims colombier inc,0.964286,0.964286,0.964286,0.964286,0.964286
1,S1-965667,S2-743505751,maure williams colombier inc,maure williams colombier,0.923077,1.000000,0.923077,1.000000,0.950000
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,0.171429,0.285714,0.114286,0.114286,0.257143
3,S1-965667,S3-11291185,maure williams colombier inc,maurewilliamscolombier com,0.888889,0.901961,0.629630,0.629630,0.888889
4,S1-965667,S3-860443364,maure williams colombier inc,maure williams inc center,0.679245,0.780488,0.830189,0.837209,0.795349
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,0.105263,0.080000,0.080000,0.103636
6,S1-55344266,S2-197070651,raj investments llp,raj investments llp,1.000000,1.000000,1.000000,1.000000,1.000000
7,S1-55344266,S3-478195123,raj investments llp,raj investments எல்எல்பி,0.744186,0.914286,0.697674,0.882353,0.838235
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.080000,0.105263,0.080000,0.080000,0.103636
9,S1-343815751,S2-790675320,dahlia power reliable scientific llc,dahlia power reliable,0.736842,1.000000,0.736842,1.000000,0.900000
10,S1-343815751,S2-479876582,dahlia power reliable scientific llc,dahlia power reliable scientific,0.941176,1.000000,0.941176,1.000000,0.950000
11,S1-343815751,S3-878454467,dahlia power reliable scientific llc,dahlia ponr reliable scientific llc,0.957746,0.942857,0.957746,0.957746,0.957746
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.146341,0.125000,0.125000,0.125000
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.146341,0.125000,0.125000,0.125000
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.146341,0.125000,0.125000,0.125000
15,S1-102811957,S2-478959098,payne enterprises,payne énterprises,0.941176,0.941176,0.647059,0.941176,0.941176
16,S1-102811957,S2-553508714,payne enterprises,payne enterpires,0.909091,0.903226,0.909091,0.909091,0.909091
17,S1-102811957,S2-625774905,payne enterprises,payne enrtprmises,0.882353,0.882353,0.882353,0.882353,0.882353
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,0.764706,0.764706,0.764706,0.764706,0.764706
19,S1-102811957,S3-928796641,payne enterprises,payne énterprises,0.941176,0.941176,0.647059,0.941176,0.941176

In [55]:
# RapidFuzz features for addresses

comparison["rf_addr_ratio"] = comparison.apply(
    lambda x: fuzz.ratio(x["s1_address"], x["matched_address"]) / 100,
    axis=1
)

comparison["rf_addr_partial"] = comparison.apply(
    lambda x: fuzz.partial_ratio(x["s1_address"], x["matched_address"]) / 100,
    axis=1
)

comparison["rf_addr_token_sort"] = comparison.apply(
    lambda x: fuzz.token_sort_ratio(x["s1_address"], x["matched_address"]) / 100,
    axis=1
)

comparison["rf_addr_token_set"] = comparison.apply(
    lambda x: fuzz.token_set_ratio(x["s1_address"], x["matched_address"]) / 100,
    axis=1
)

comparison["rf_addr_wratio"] = comparison.apply(
    lambda x: fuzz.WRatio(x["s1_address"], x["matched_address"]) / 100,
    axis=1
)

display(
    comparison[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "rf_addr_ratio",
            "rf_addr_partial",
            "rf_addr_token_sort",
            "rf_addr_token_set",
            "rf_addr_wratio",
            "country_match"
        ]
    ].head(20)
)

,s1_id,matched_id,s1_name,matched_name,rf_addr_ratio,rf_addr_partial,rf_addr_token_sort,rf_addr_token_set,rf_addr_wratio,country_match
0,S1-965667,S2-681193310,maure williams colombier inc,maure wilblims colombier inc,0.000000,0.000000,0.000000,0.000000,0.000000,True
1,S1-965667,S2-743505751,maure williams colombier inc,maure williams colombier,0.000000,0.000000,0.000000,0.000000,0.000000,True
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,0.763158,0.931034,0.736842,0.823529,0.855000,True
3,S1-965667,S3-11291185,maure williams colombier inc,maurewilliamscolombier com,0.685714,0.846154,0.657143,0.742857,0.705714,True
4,S1-965667,S3-860443364,maure williams colombier inc,maure williams inc center,0.000000,0.000000,0.000000,0.000000,0.000000,True
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,1.000000,1.000000,1.000000,1.000000,1.000000,True
6,S1-55344266,S2-197070651,raj investments llp,raj investments llp,1.000000,1.000000,1.000000,1.000000,1.000000,True
7,S1-55344266,S3-478195123,raj investments llp,raj investments எல்எல்பி,0.927273,0.990099,0.909091,0.969697,0.927273,True
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.837607,0.915888,0.837607,0.905660,0.860377,True
9,S1-343815751,S2-790675320,dahlia power reliable scientific llc,dahlia power reliable,0.477612,0.622222,0.865672,0.912281,0.866667,True
10,S1-343815751,S2-479876582,dahlia power reliable scientific llc,dahlia power reliable scientific,0.793651,0.779661,0.793651,0.830189,0.793651,True
11,S1-343815751,S3-878454467,dahlia power reliable scientific llc,dahlia ponr reliable scientific llc,0.823529,0.949153,0.911765,0.949153,0.901695,True
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.767442,0.855263,0.848837,0.883117,0.838961,True
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.400000,0.545455,0.608000,0.931507,0.855000,True
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.361905,0.684211,0.342857,0.914286,0.855000,True
15,S1-102811957,S2-478959098,payne enterprises,payne énterprises,0.925926,0.840000,0.925926,0.936170,0.925926,True
16,S1-102811957,S2-553508714,payne enterprises,payne enterpires,0.925926,0.840000,0.925926,0.936170,0.925926,True
17,S1-102811957,S2-625774905,payne enterprises,payne enrtprmises,0.877193,0.857143,0.877193,0.880000,0.877193,True
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,0.833333,0.925926,0.833333,0.833333,0.833333,True
19,S1-102811957,S3-928796641,payne enterprises,payne énterprises,0.906250,1.000000,0.906250,0.945455,0.906250,True

In [56]:
import re

def extract_numbers(text):
    if not text:
        return set()
    
    # Extract complete numeric sequences
    return set(re.findall(r'\d+', text))


def number_overlap(a, b):
    nums_a = extract_numbers(a)
    nums_b = extract_numbers(b)
    
    if not nums_a or not nums_b:
        return 0.0
    
    intersection = nums_a & nums_b
    union = nums_a | nums_b
    
    return len(intersection) / len(union) if union else 0.0


def exact_match(a, b):
    return 1.0 if a and b and a == b else 0.0


comparison["name_exact"] = comparison.apply(
    lambda x: exact_match(x["s1_name"], x["matched_name"]),
    axis=1
)

comparison["address_exact"] = comparison.apply(
    lambda x: exact_match(x["s1_address"], x["matched_address"]),
    axis=1
)

comparison["address_number_overlap"] = comparison.apply(
    lambda x: number_overlap(x["s1_address"], x["matched_address"]),
    axis=1
)

display(
    comparison[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_exact",
            "address_exact",
            "address_number_overlap",
            "rf_addr_ratio",
            "rf_addr_token_set",
            "country_match"
        ]
    ].head(20)
)

,s1_id,matched_id,s1_name,matched_name,s1_address,matched_address,name_exact,address_exact,address_number_overlap,rf_addr_ratio,rf_addr_token_set,country_match
0,S1-965667,S2-681193310,maure williams colombier inc,maure wilblims colombier inc,85 wayne avenue ticonderoga ny,,0.0,0.0,0.000000,0.000000,0.000000,True
1,S1-965667,S2-743505751,maure williams colombier inc,maure williams colombier,85 wayne avenue ticonderoga ny,,0.0,0.0,0.000000,0.000000,0.000000,True
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,85 wayne avenue ticonderoga ny,85 wanye avenue ticonderoga townshiip new york,0.0,0.0,1.000000,0.763158,0.823529,True
3,S1-965667,S3-11291185,maure williams colombier inc,maurewilliamscolombier com,85 wayne avenue ticonderoga ny,wayne ave ticonderoga townshiip new york,0.0,0.0,0.000000,0.685714,0.742857,True
4,S1-965667,S3-860443364,maure williams colombier inc,maure williams inc center,85 wayne avenue ticonderoga ny,,0.0,0.0,0.000000,0.000000,0.000000,True
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,0.0,1.0,1.000000,1.000000,1.000000,True
6,S1-55344266,S2-197070651,raj investments llp,raj investments llp,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,1.0,1.0,1.000000,1.000000,1.000000,True
7,S1-55344266,S3-478195123,raj investments llp,raj investments எல்எல்பி,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,0.0,0.0,1.000000,0.927273,0.969697,True
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,6 29 c i t colony 2nd main road mylapore chenn...,6 29 c i t colony 2nd main road mylapore chenn...,0.0,0.0,1.000000,0.837607,0.905660,True
9,S1-343815751,S2-790675320,dahlia power reliable scientific llc,dahlia power reliable,630 45th terrace kansas city mo,kansas city mo 630 45nd terrace null,0.0,0.0,1.000000,0.477612,0.912281,True
10,S1-343815751,S2-479876582,dahlia power reliable scientific llc,dahlia power reliable scientific,630 45th terrace kansas city mo,45nd terrace null kansas city mo,0.0,0.0,0.500000,0.793651,0.830189,True
11,S1-343815751,S3-878454467,dahlia power reliable scientific llc,dahlia ponr reliable scientific llc,630 45th terrace kansas city mo,missouri 630 45th terrace kansas city,0.0,0.0,1.000000,0.823529,0.949153,True
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,af 684 nandgram near mother india public schoo...,af 0684 nandgram near mother india public scho...,0.0,0.0,0.500000,0.767442,0.883117,True
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,af 684 nandgram near mother india public schoo...,af 0684 uttar pradesh ghaziabad 9487203,0.0,0.0,0.250000,0.400000,0.931507,True
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,af 684 nandgram near mother india public schoo...,af 684 ghaziabad up,0.0,0.0,0.333333,0.361905,0.914286,True
15,S1-102811957,S2-478959098,payne enterprises,payne énterprises,3315 fremont street peoria il,3315 fremont st peoria il,0.0,0.0,1.000000,0.925926,0.936170,True
16,S1-102811957,S2-553508714,payne enterprises,payne enterpires,3315 fremont street peoria il,3315 fremont st peoria il,0.0,0.0,1.000000,0.925926,0.936170,True
17,S1-102811957,S2-625774905,payne enterprises,payne enrtprmises,3315 fremont street peoria il,3315 fremont saint peoria il,0.0,0.0,1.000000,0.877193,0.880000,True
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,3315 fremont street peoria il,3315 fremont st peoria illinois,0.0,0.0,1.000000,0.833333,0.833333,True
19,S1-102811957,S3-928796641,payne enterprises,payne énterprises,3315 fremont street peoria il,3315 fremont street peoria illinois,0.0,0.0,1.000000,0.906250,0.945455,True

In [57]:
feature_columns = [
    "rf_ratio",
    "rf_partial",
    "rf_token_sort",
    "rf_token_set",
    "rf_wratio",
    "rf_addr_ratio",
    "rf_addr_partial",
    "rf_addr_token_sort",
    "rf_addr_token_set",
    "rf_addr_wratio",
    "name_exact",
    "address_exact",
    "address_number_overlap",
    "country_match"
]

feature_summary = comparison[feature_columns].describe().T

display(feature_summary)

,count,mean,std,min,25%,50%,75%,max
rf_ratio,70.0,0.720076,0.288024,0.080000,0.648085,0.816667,0.920879,1.0
rf_partial,70.0,0.806172,0.290140,0.093023,0.824544,0.930952,1.000000,1.0
rf_token_sort,70.0,0.716085,0.294323,0.080000,0.624940,0.815094,0.938416,1.0
rf_token_set,70.0,0.804170,0.306538,0.080000,0.824544,0.941176,1.000000,1.0
rf_wratio,70.0,0.786235,0.288198,0.080000,0.788492,0.900000,0.950000,1.0
rf_addr_ratio,70.0,0.699083,0.307329,0.000000,0.573733,0.828431,0.925926,1.0
rf_addr_partial,70.0,0.755253,0.303330,0.000000,0.692308,0.856203,0.961538,1.0
rf_addr_token_sort,70.0,0.735273,0.301374,0.000000,0.703498,0.866169,0.925926,1.0
rf_addr_token_set,70.0,0.799979,0.301211,0.000000,0.825194,0.910686,0.955224,1.0
rf_addr_wratio,70.0,0.783448,0.292922,0.000000,0.811077,0.862007,0.938025,1.0
name_exact,70.0,0.114286,0.320455,0.000000,0.000000,0.000000,0.000000,1.0
address_exact,70.0,0.128571,0.337142,0.000000,0.000000,0.000000,0.000000,1.0
address_number_overlap,70.0,0.665000,0.410394,0.000000,0.350000,1.000000,1.000000,1.0

In [58]:
# Show the hardest known-correct matches
hardest_matches = comparison.sort_values(
    by=["rf_wratio", "rf_addr_wratio"]
).head(15)

display(
    hardest_matches[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "rf_wratio",
            "rf_addr_wratio",
            "address_number_overlap",
            "country_match"
        ]
    ]
)

,s1_id,matched_id,s1_name,matched_name,rf_wratio,rf_addr_wratio,address_number_overlap,country_match
31,S1-789009573,S2-383871912,hotel enterprises limited,होटल एंटरप्राइजेज लिमिटेड,0.080000,0.855000,0.500000,True
64,S1-561341312,S2-483615364,balaji investment private limited,బాలాజీ ఇన్వెస్ట్ మెంట్ ప్రైవేట్ లిమిటెడ్,0.082192,0.950000,0.666667,True
8,S1-55344266,S3-384364074,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.103636,0.860377,1.000000,True
5,S1-55344266,S2-249013014,raj investments llp,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,0.103636,1.000000,1.000000,True
25,S1-318373630,S2-660036492,red ventures private limited,रेड वेंचर्स प्राइवेट लिमिटेड,0.107143,0.855000,0.500000,True
12,S1-656753428,S2-153058913,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.838961,0.500000,True
13,S1-656753428,S2-24659151,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.855000,0.250000,True
14,S1-656753428,S3-679606215,ss food private limited,एसएस फूड प्राइवेट लिमिटेड,0.125000,0.855000,0.333333,True
67,S1-777597828,S3-413669121,uptown pub,solkeloquo,0.200000,0.783784,0.500000,True
2,S1-965667,S3-775321672,maure williams colombier inc,dréxkor,0.257143,0.855000,1.000000,True
58,S1-503957000,S2-173295926,ap hospitality inc,ap ínc center,0.429032,1.000000,1.000000,True
55,S1-503957000,S2-994658326,ap hospitality inc,ap inc service 80430,0.475000,1.000000,1.000000,True
39,S1-7293388,S3-523120965,chordia partners,smt chordia center,0.670588,0.809259,1.000000,True
18,S1-102811957,S3-728090388,payne enterprises,payne etrepndiels,0.764706,0.833333,1.000000,True
32,S1-789009573,S3-74481402,hotel enterprises limited,hotel limited services,0.768085,0.855000,0.400000,True

In [59]:
# Build the 20 labeled S1 records we are currently studying
s1_labeled = s1_gt.copy()

# Candidate records from our 10k samples
s2_candidates = s2.copy()
s3_candidates = s3.copy()

print("S1 labeled records:", len(s1_labeled))
print("S2 candidate records:", len(s2_candidates))
print("S3 candidate records:", len(s3_candidates))

S1 labeled records: 20
S2 candidate records: 10000
S3 candidate records: 10000

In [60]:
# All known positive S2/S3 IDs from our ground truth
known_positive_ids = set(matched_ids)

print("Known positive IDs:", len(known_positive_ids))

Known positive IDs: 70

In [61]:
s2_candidates = s2_candidates[
    ~s2_candidates["entity_id"].isin(known_positive_ids)
].copy()

s3_candidates = s3_candidates[
    ~s3_candidates["entity_id"].isin(known_positive_ids)
].copy()

print("S2 negative candidate pool:", len(s2_candidates))
print("S3 negative candidate pool:", len(s3_candidates))

S2 negative candidate pool: 10000
S3 negative candidate pool: 10000

In [62]:
import random

random.seed(42)

negative_rows = []

# Number of random negatives per labeled S1
NEGATIVES_PER_S1 = 20

for _, s1_row in s1_labeled.iterrows():
    
    # Random S2 negatives
    s2_sample = s2_candidates.sample(
        n=NEGATIVES_PER_S1,
        random_state=42
    )
    
    for _, s2_row in s2_sample.iterrows():
        negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": s2_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": s2_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": s2_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": s2_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == s2_row["country_norm"]
            ),
            "label": 0
        })
    
    # Random S3 negatives
    s3_sample = s3_candidates.sample(
        n=NEGATIVES_PER_S1,
        random_state=42
    )
    
    for _, s3_row in s3_sample.iterrows():
        negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": s3_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": s3_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": s3_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": s3_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == s3_row["country_norm"]
            ),
            "label": 0
        })

random_negatives = pd.DataFrame(negative_rows)

print("Random negative pairs:", len(random_negatives))
print("S2 negatives:", sum(random_negatives["matched_id"].str.startswith("S2-")))
print("S3 negatives:", sum(random_negatives["matched_id"].str.startswith("S3-")))

Random negative pairs: 800
S2 negatives: 400
S3 negatives: 400

In [63]:
from rapidfuzz import process, fuzz

# Number of hard candidates we want for each S1
HARD_CANDIDATES_PER_S1 = 10

hard_negative_rows = []

for _, s1_row in s1_labeled.iterrows():
    
    s1_name = s1_row["business_name_norm"]
    
    # Find highly similar S2 names
    s2_results = process.extract(
        s1_name,
        s2_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )
    
    for matched_name, score, idx in s2_results:
        matched_row = s2_candidates.iloc[idx]
        
        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })
    
    # Find highly similar S3 names
    s3_results = process.extract(
        s1_name,
        s3_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )
    
    for matched_name, score, idx in s3_results:
        matched_row = s3_candidates.iloc[idx]
        
        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })

hard_negatives = pd.DataFrame(hard_negative_rows)

print("Hard negative candidates:", len(hard_negatives))
print(
    "S2 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S2-"))
)
print(
    "S3 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S3-"))
)

Hard negative candidates: 400
S2 hard negatives: 200
S3 hard negatives: 200

In [64]:
# Show the highest name-similarity candidates

hardest_candidates = hard_negatives.sort_values(
    by="name_score",
    ascending=False
).head(30)

display(
    hardest_candidates[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "name_score",
            "country_match"
        ]
    ]
)

,s1_id,matched_id,s1_name,matched_name,s1_address,matched_address,name_score,country_match
290,S1-789009573,S3-47523244,hotel enterprises limited,hotel enterprises private limited,wz 187c shop no 13 14 kh no 47 s f vikaspuri b...,44 15 kailash colony anna nagar west chennai c...,0.950000,True
70,S1-777597828,S3-779940792,uptown pub,uptown pub inc,6114 10th avenue spokane valley wa,,0.950000,True
90,S1-318373630,S3-588841502,red ventures private limited,6reen ventures private limited,rajasthan jaipur banipark gokul apartment e 3a...,cm 74 c sector shahpura bhopal mp,0.931034,True
370,S1-561341312,S3-418232358,balaji investment private limited,alpha investment private limited,plot no d 88 d 90 hyd telangana hyderabad jeed...,7 9 ground floor akshay complex off dhole pati...,0.923077,True
91,S1-318373630,S3-760013898,red ventures private limited,east ventures private limited,rajasthan jaipur banipark gokul apartment e 3a...,g 5 sitapura jaipur rj,0.912281,True
92,S1-318373630,S3-368460950,red ventures private limited,blue ventures private limited,rajasthan jaipur banipark gokul apartment e 3a...,door no 00946 4 74 vikas nagar rampur lucknow up,0.912281,True
12,S1-274126313,S3-138123826,obsidian llc,obsidian,3907 hamilton road deer park wa,4612 st rt 95 perrysvlile ohio,0.900000,True
11,S1-274126313,S3-876557761,obsidian llc,ectoveraveo t a obsidian llc,3907 hamilton road deer park wa,218 death rock way whitehall ny,0.900000,True
10,S1-274126313,S3-904389726,obsidian llc,lc,3907 hamilton road deer park wa,hari sudharshana carnival no 6 coimbatore tami...,0.900000,False
13,S1-274126313,S3-664802217,obsidian llc,si,3907 hamilton road deer park wa,ghaziabad uttar pradesh shyam park shahibabad ...,0.900000,False
0,S1-274126313,S2-406460695,obsidian llc,obsidian,3907 hamilton road deer park wa,4250 geiegr road millersport oh,0.900000,True
110,S1-7293388,S3-601550279,chordia partners,rs,faridabad 1038 sector 9 haryana,h n 2628 khakhad tola post dudahi padrauna kus...,0.900000,True
250,S1-503957000,S3-261239034,ap hospitality inc,hospitality,20085 us 23 circleville oh,c o shlok agrawal opp head post office near ra...,0.900000,False
340,S1-55344266,S2-367915011,raj investments llp,investments,6 29 c i t colony 2nd main road mylapore chenn...,4346 indian road toledo oh,0.900000,False
160,S1-730934468,S2-367915011,orellana investments llc,investments,728 a quail avenue fl ground floor geneva ia,4346 indian road toledo oh,0.900000,True
120,S1-86989137,S2-367915011,laxmi golden investments private limited,investments,new bridge business centre s 11th floor n1 blo...,4346 indian road toledo oh,0.900000,False
93,S1-318373630,S3-881433812,red ventures private limited,surya ventures private limited,rajasthan jaipur banipark gokul apartment e 3a...,l 5 c r park new delhi dl,0.896552,True
80,S1-318373630,S2-630772014,red ventures private limited,ram ventures private límited,rajasthan jaipur banipark gokul apartment e 3a...,h no 4 59 gangavaram village kothaambapuram gu...,0.892857,True
121,S1-86989137,S2-830436713,laxmi golden investments private limited,private maa investments limited,new bridge business centre s 11th floor n1 blo...,7th main 3rd e cross maruthi layout vasanthapu...,0.884483,True
130,S1-86989137,S3-490107025,laxmi golden investments private limited,red investments private limited,new bridge business centre s 11th floor n1 blo...,j 1 28a 1st floor khirki extension new delhi m...,0.884483,True
183,S1-656753428,S2-495700782,ss food private limited,bangalore food private limited,af 684 nandgram near mother india public schoo...,hn 415 genna software solutions ltd flat s 1 c...,0.883721,True
190,S1-656753428,S3-84322725,ss food private limited,nirman food private limited,af 684 nandgram near mother india public schoo...,g081 madhavpark vadodara tarsali gj,0.883721,True
182,S1-656753428,S2-515012790,ss food private limited,uay private overseas food limited,af 684 nandgram near mother india public schoo...,h no 059 basement b block krishna park vikash ...,0.883721,True
191,S1-656753428,S3-370453514,ss food private limited,vision food private limited,af 684 nandgram near mother india public schoo...,no 668 sy no 229 230 235 b proddatur meenapura...,0.883721,True
181,S1-656753428,S2-44619810,ss food private limited,clockwork food private limited,af 684 nandgram near mother india public schoo...,door no 139 eg office no 216 surbhi mall compl...,0.883721,True
180,S1-656753428,S2-164651728,ss food private limited,private shiv food limited,af 684 nandgram near mother india public schoo...,new delhi new friends colony a 211 delhi,0.883721,True
371,S1-561341312,S3-408212372,balaji investment private limited,urban investments private limited,plot no d 88 d 90 hyd telangana hyderabad jeed...,sco 3 1st floor bhagwati tower kunjpura road k...,0.878788,True
372,S1-561341312,S3-75072595,balaji investment private limited,royal investments private limited,plot no d 88 d 90 hyd telangana hyderabad jeed...,fourth floor no 2651 2 nd cross 15 th main â e...,0.878788,True
96,S1-318373630,S3-962806873,red ventures private limited,ventures shell support private limited,rajasthan jaipur banipark gokul apartment e 3a...,5 9 254 hyderabad andhra pradesh,0.876923,True
94,S1-318373630,S3-901865937,red ventures private limited,aroma brdthters ventures private limited,rajasthan jaipur banipark gokul apartment e 3a...,mh h no 345 at bhilwale khalapur raigarh bhilvale,0.876923,True

In [2]:
from rapidfuzz import process, fuzz

HARD_CANDIDATES_PER_S1 = 10

hard_negative_rows = []

for _, s1_row in s1_labeled.iterrows():

    s1_name = s1_row["business_name_norm"]

    # S2 hard candidates
    s2_results = process.extract(
        s1_name,
        s2_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )

    for matched_name, score, idx in s2_results:
        matched_row = s2_candidates.iloc[idx]

        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })

    # S3 hard candidates
    s3_results = process.extract(
        s1_name,
        s3_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )

    for matched_name, score, idx in s3_results:
        matched_row = s3_candidates.iloc[idx]

        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })

hard_negatives = pd.DataFrame(hard_negative_rows)

print("Hard negative candidates:", len(hard_negatives))
print(
    "S2 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S2-"))
)
print(
    "S3 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S3-"))
)

ModuleNotFoundError: No module named 'rapidfuzz'

In [7]:
!pip install rapidfuzz -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 25.8 MB/s eta 0:00:0000:0100:01

In [8]:
from rapidfuzz import fuzz, process

print("RapidFuzz is working!")
print(fuzz.ratio("payne enterprises", "payne enterpires"))

RapidFuzz is working!
90.9090909090909

In [9]:
print("s1_labeled:", "s1_labeled" in globals())
print("s2_candidates:", "s2_candidates" in globals())
print("s3_candidates:", "s3_candidates" in globals())
print("matched_ids:", "matched_ids" in globals())

s1_labeled: False
s2_candidates: False
s3_candidates: False
matched_ids: False

In [6]:
import pandas as pd
import numpy as np
import glob
import os
import re
import unicodedata

# --------------------------------------------------
# 1. Find the dataset files again
# --------------------------------------------------

files = glob.glob("/kaggle/input/**/*.tsv", recursive=True)

file_paths = {
    os.path.basename(file): file
    for file in files
}

print("Files found:", len(file_paths))


# --------------------------------------------------
# 2. Normalization function
# --------------------------------------------------

def normalize_text(text):
    if not text:
        return ""

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Replace punctuation/symbols with spaces
    # while preserving letters/numbers from non-Latin scripts
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)

    # Remove underscores
    text = text.replace("_", " ")

    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


# --------------------------------------------------
# 3. Legal suffix removal
# --------------------------------------------------

LEGAL_SUFFIXES = [
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "public limited",
    "public ltd",
    "holding company",
    "limited liability company",
    "company",
    "corporation",
    "incorporated",
    "limited",
    "llp",
    "llc",
    "corp",
    "inc",
    "pvt",
    "ltd",
    "co"
]

def remove_legal_suffix(name):
    if not name:
        return ""

    name = name.strip()

    changed = True

    while changed:
        changed = False

        for suffix in sorted(LEGAL_SUFFIXES, key=len, reverse=True):
            pattern = rf"\s+{re.escape(suffix)}$"

            if re.search(pattern, name):
                name = re.sub(pattern, "", name).strip()
                changed = True
                break

    return name


# --------------------------------------------------
# 4. Reload the 10k candidate samples
# --------------------------------------------------

SAMPLE_SIZE = 10000

s1 = pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)

s2 = pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)

s3 = pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=SAMPLE_SIZE
)


# --------------------------------------------------
# 5. Recreate normalized columns
# --------------------------------------------------

for df in [s1, s2, s3]:

    df["business_name_norm"] = (
        df["business_name"].map(normalize_text)
    )

    df["business_address_norm"] = (
        df["business_address"].map(normalize_text)
    )

    df["country_norm"] = (
        df["country"].map(normalize_text)
    )

    df["business_name_core"] = (
        df["business_name_norm"].map(remove_legal_suffix)
    )


# --------------------------------------------------
# 6. Load the 20 ground-truth rows
# --------------------------------------------------

ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    nrows=20
)

s1_ids = ground_truth["source1_entity_id"].tolist()


# --------------------------------------------------
# 7. Retrieve those 20 S1 records from full S1
# --------------------------------------------------

target_ids = set(s1_ids)

s1_matches = []

for chunk in pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):

    found = chunk[
        chunk["entity_id"].isin(target_ids)
    ]

    if not found.empty:
        s1_matches.append(found)


s1_gt = pd.concat(
    s1_matches,
    ignore_index=True
)


# Recreate normalized fields for the labeled S1 records

s1_gt["business_name_norm"] = (
    s1_gt["business_name"].map(normalize_text)
)

s1_gt["business_address_norm"] = (
    s1_gt["business_address"].map(normalize_text)
)

s1_gt["country_norm"] = (
    s1_gt["country"].map(normalize_text)
)

s1_gt["business_name_core"] = (
    s1_gt["business_name_norm"].map(remove_legal_suffix)
)


# --------------------------------------------------
# 8. This is our labeled S1 dataframe
# --------------------------------------------------

s1_labeled = s1_gt.copy()


# --------------------------------------------------
# 9. Recover all known positive S2/S3 IDs
# --------------------------------------------------

matched_ids = set()

for value in ground_truth["matched_entity_ids"]:

    for entity_id in value.split(","):

        entity_id = entity_id.strip()

        if entity_id:
            matched_ids.add(entity_id)


known_positive_ids = set(matched_ids)


# --------------------------------------------------
# 10. Create candidate pools
# --------------------------------------------------

s2_candidates = s2[
    ~s2["entity_id"].isin(known_positive_ids)
].copy()

s3_candidates = s3[
    ~s3["entity_id"].isin(known_positive_ids)
].copy()


# --------------------------------------------------
# 11. Verify recovery
# --------------------------------------------------

print()
print("===== RECOVERY CHECK =====")
print("S1 labeled records:", len(s1_labeled))
print("S2 candidate records:", len(s2_candidates))
print("S3 candidate records:", len(s3_candidates))
print("Known positive IDs:", len(known_positive_ids))
print()
print("S1 columns:", len(s1_labeled.columns))
print("S2 columns:", len(s2_candidates.columns))
print("S3 columns:", len(s3_candidates.columns))

Files found: 7

===== RECOVERY CHECK =====
S1 labeled records: 20
S2 candidate records: 10000
S3 candidate records: 10000
Known positive IDs: 70

S1 columns: 8
S2 columns: 8
S3 columns: 8

In [7]:
from rapidfuzz import process, fuzz

HARD_CANDIDATES_PER_S1 = 10

hard_negative_rows = []

for _, s1_row in s1_labeled.iterrows():

    s1_name = s1_row["business_name_norm"]

    # S2 hard candidates
    s2_results = process.extract(
        s1_name,
        s2_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )

    for matched_name, score, idx in s2_results:
        matched_row = s2_candidates.iloc[idx]

        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })

    # S3 hard candidates
    s3_results = process.extract(
        s1_name,
        s3_candidates["business_name_norm"],
        scorer=fuzz.WRatio,
        limit=HARD_CANDIDATES_PER_S1
    )

    for matched_name, score, idx in s3_results:
        matched_row = s3_candidates.iloc[idx]

        hard_negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": matched_row["entity_id"],
            "s1_name": s1_row["business_name_norm"],
            "matched_name": matched_row["business_name_norm"],
            "s1_core": s1_row["business_name_core"],
            "matched_core": matched_row["business_name_core"],
            "s1_address": s1_row["business_address_norm"],
            "matched_address": matched_row["business_address_norm"],
            "country_match": (
                s1_row["country_norm"] == matched_row["country_norm"]
            ),
            "name_score": score / 100,
            "label": 0
        })

hard_negatives = pd.DataFrame(hard_negative_rows)

print("Hard negative candidates:", len(hard_negatives))
print(
    "S2 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S2-"))
)
print(
    "S3 hard negatives:",
    sum(hard_negatives["matched_id"].str.startswith("S3-"))
)

Hard negative candidates: 400
S2 hard negatives: 200
S3 hard negatives: 200

In [8]:
# Calculate address similarity features for hard-negative candidates

hard_negatives["rf_addr_ratio"] = hard_negatives.apply(
    lambda x: fuzz.ratio(
        x["s1_address"],
        x["matched_address"]
    ) / 100,
    axis=1
)

hard_negatives["rf_addr_partial"] = hard_negatives.apply(
    lambda x: fuzz.partial_ratio(
        x["s1_address"],
        x["matched_address"]
    ) / 100,
    axis=1
)

hard_negatives["rf_addr_token_sort"] = hard_negatives.apply(
    lambda x: fuzz.token_sort_ratio(
        x["s1_address"],
        x["matched_address"]
    ) / 100,
    axis=1
)

hard_negatives["rf_addr_token_set"] = hard_negatives.apply(
    lambda x: fuzz.token_set_ratio(
        x["s1_address"],
        x["matched_address"]
    ) / 100,
    axis=1
)

hard_negatives["rf_addr_wratio"] = hard_negatives.apply(
    lambda x: fuzz.WRatio(
        x["s1_address"],
        x["matched_address"]
    ) / 100,
    axis=1
)

hard_negatives["address_number_overlap"] = hard_negatives.apply(
    lambda x: number_overlap(
        x["s1_address"],
        x["matched_address"]
    ),
    axis=1
)

print("Address features calculated successfully.")

NameError: name 'number_overlap' is not defined

In [11]:
import re

def extract_numbers(text):
    if not text:
        return set()
    
    return set(re.findall(r'\d+', text))


def number_overlap(a, b):
    nums_a = extract_numbers(a)
    nums_b = extract_numbers(b)

    if not nums_a or not nums_b:
        return 0.0

    intersection = nums_a & nums_b
    union = nums_a | nums_b

    return len(intersection) / len(union) if union else 0.0

In [12]:
hard_negatives["address_number_overlap"] = hard_negatives.apply(
    lambda x: number_overlap(
        x["s1_address"],
        x["matched_address"]
    ),
    axis=1
)

print("Address number overlap calculated successfully.")

Address number overlap calculated successfully.

In [13]:
display(
    hard_negatives.sort_values(
        by=["name_score", "rf_addr_wratio"],
        ascending=[False, True]
    ).head(30)[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "name_score",
            "rf_addr_wratio",
            "rf_addr_token_set",
            "address_number_overlap",
            "country_match"
        ]
    ]
)

,s1_id,matched_id,s1_name,matched_name,name_score,rf_addr_wratio,rf_addr_token_set,address_number_overlap,country_match
70,S1-777597828,S3-779940792,uptown pub,uptown pub inc,0.950000,0.000000,0.000000,0.000000,True
290,S1-789009573,S3-47523244,hotel enterprises limited,hotel enterprises private limited,0.950000,0.855000,0.430556,0.000000,True
90,S1-318373630,S3-588841502,red ventures private limited,6reen ventures private limited,0.931034,0.387692,0.333333,0.000000,True
370,S1-561341312,S3-418232358,balaji investment private limited,alpha investment private limited,0.923077,0.360345,0.379310,0.000000,True
92,S1-318373630,S3-368460950,red ventures private limited,blue ventures private limited,0.912281,0.324786,0.341880,0.000000,True
91,S1-318373630,S3-760013898,red ventures private limited,east ventures private limited,0.912281,0.855000,0.533333,0.000000,True
250,S1-503957000,S3-261239034,ap hospitality inc,hospitality,0.900000,0.311538,0.230769,0.000000,False
12,S1-274126313,S3-138123826,obsidian llc,obsidian,0.900000,0.342623,0.360656,0.000000,True
120,S1-86989137,S2-367915011,laxmi golden investments private limited,investments,0.900000,0.346154,0.200000,0.000000,False
160,S1-730934468,S2-367915011,orellana investments llc,investments,0.900000,0.380769,0.314286,0.000000,True
110,S1-7293388,S3-601550279,chordia partners,rs,0.900000,0.406452,0.408163,0.000000,True
11,S1-274126313,S3-876557761,obsidian llc,ectoveraveo t a obsidian llc,0.900000,0.429032,0.451613,0.000000,True
10,S1-274126313,S3-904389726,obsidian llc,lc,0.900000,0.435484,0.333333,0.000000,False
0,S1-274126313,S2-406460695,obsidian llc,obsidian,0.900000,0.520968,0.548387,0.000000,True
13,S1-274126313,S3-664802217,obsidian llc,si,0.900000,0.855000,0.444444,0.000000,False
340,S1-55344266,S2-367915011,raj investments llp,investments,0.900000,0.855000,0.400000,0.000000,False
93,S1-318373630,S3-881433812,red ventures private limited,surya ventures private limited,0.896552,0.376200,0.297872,0.000000,True
80,S1-318373630,S2-630772014,red ventures private limited,ram ventures private límited,0.892857,0.426667,0.426667,0.000000,True
121,S1-86989137,S2-830436713,laxmi golden investments private limited,private maa investments limited,0.884483,0.523784,0.551351,0.000000,True
130,S1-86989137,S3-490107025,laxmi golden investments private limited,red investments private limited,0.884483,0.855000,0.493976,0.333333,True
180,S1-656753428,S2-164651728,ss food private limited,private shiv food limited,0.883721,0.360000,0.241379,0.000000,True
190,S1-656753428,S3-84322725,ss food private limited,nirman food private limited,0.883721,0.360000,0.330579,0.000000,True
183,S1-656753428,S2-495700782,ss food private limited,bangalore food private limited,0.883721,0.363636,0.382775,0.000000,True
181,S1-656753428,S2-44619810,ss food private limited,clockwork food private limited,0.883721,0.371257,0.378049,0.000000,True
182,S1-656753428,S2-515012790,ss food private limited,uay private overseas food limited,0.883721,0.380000,0.400000,0.000000,True
191,S1-656753428,S3-370453514,ss food private limited,vision food private limited,0.883721,0.391875,0.407643,0.000000,True
371,S1-561341312,S3-408212372,balaji investment private limited,urban investments private limited,0.878788,0.328846,0.346154,0.000000,True
372,S1-561341312,S3-75072595,balaji investment private limited,royal investments private limited,0.878788,0.855000,0.323077,0.000000,True
87,S1-318373630,S2-598596199,red ventures private limited,grn chrotre ventures private limited,0.876923,0.293906,0.316832,0.000000,True
84,S1-318373630,S2-690767550,red ventures private limited,dr lakshmi ventures private limited,0.876923,0.355932,0.355932,0.000000,True

In [14]:
hard_negative_clean = hard_negatives[
    (hard_negatives["name_score"] >= 0.85) &
    (hard_negatives["rf_addr_wratio"] < 0.60)
].copy()

print("Clean hard negatives:", len(hard_negative_clean))

print(
    "S2:",
    sum(
        hard_negative_clean["matched_id"].str.startswith("S2-")
    )
)

print(
    "S3:",
    sum(
        hard_negative_clean["matched_id"].str.startswith("S3-")
    )
)

Clean hard negatives: 356
S2: 180
S3: 176

In [15]:
display(
    hard_negative_clean.sort_values(
        by="name_score",
        ascending=False
    ).head(30)[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "name_score",
            "rf_addr_wratio",
            "rf_addr_token_set",
            "address_number_overlap",
            "country_match"
        ]
    ]
)

,s1_id,matched_id,s1_name,matched_name,name_score,rf_addr_wratio,rf_addr_token_set,address_number_overlap,country_match
70,S1-777597828,S3-779940792,uptown pub,uptown pub inc,0.950000,0.000000,0.000000,0.0,True
90,S1-318373630,S3-588841502,red ventures private limited,6reen ventures private limited,0.931034,0.387692,0.333333,0.0,True
370,S1-561341312,S3-418232358,balaji investment private limited,alpha investment private limited,0.923077,0.360345,0.379310,0.0,True
92,S1-318373630,S3-368460950,red ventures private limited,blue ventures private limited,0.912281,0.324786,0.341880,0.0,True
11,S1-274126313,S3-876557761,obsidian llc,ectoveraveo t a obsidian llc,0.900000,0.429032,0.451613,0.0,True
250,S1-503957000,S3-261239034,ap hospitality inc,hospitality,0.900000,0.311538,0.230769,0.0,False
110,S1-7293388,S3-601550279,chordia partners,rs,0.900000,0.406452,0.408163,0.0,True
12,S1-274126313,S3-138123826,obsidian llc,obsidian,0.900000,0.342623,0.360656,0.0,True
120,S1-86989137,S2-367915011,laxmi golden investments private limited,investments,0.900000,0.346154,0.200000,0.0,False
160,S1-730934468,S2-367915011,orellana investments llc,investments,0.900000,0.380769,0.314286,0.0,True
0,S1-274126313,S2-406460695,obsidian llc,obsidian,0.900000,0.520968,0.548387,0.0,True
10,S1-274126313,S3-904389726,obsidian llc,lc,0.900000,0.435484,0.333333,0.0,False
93,S1-318373630,S3-881433812,red ventures private limited,surya ventures private limited,0.896552,0.376200,0.297872,0.0,True
80,S1-318373630,S2-630772014,red ventures private limited,ram ventures private límited,0.892857,0.426667,0.426667,0.0,True
121,S1-86989137,S2-830436713,laxmi golden investments private limited,private maa investments limited,0.884483,0.523784,0.551351,0.0,True
190,S1-656753428,S3-84322725,ss food private limited,nirman food private limited,0.883721,0.360000,0.330579,0.0,True
183,S1-656753428,S2-495700782,ss food private limited,bangalore food private limited,0.883721,0.363636,0.382775,0.0,True
191,S1-656753428,S3-370453514,ss food private limited,vision food private limited,0.883721,0.391875,0.407643,0.0,True
182,S1-656753428,S2-515012790,ss food private limited,uay private overseas food limited,0.883721,0.380000,0.400000,0.0,True
181,S1-656753428,S2-44619810,ss food private limited,clockwork food private limited,0.883721,0.371257,0.378049,0.0,True
180,S1-656753428,S2-164651728,ss food private limited,private shiv food limited,0.883721,0.360000,0.241379,0.0,True
371,S1-561341312,S3-408212372,balaji investment private limited,urban investments private limited,0.878788,0.328846,0.346154,0.0,True
89,S1-318373630,S2-194063396,red ventures private limited,amay chit ventures private limited,0.876923,0.365839,0.385093,0.0,True
86,S1-318373630,S2-715553627,red ventures private limited,pivot 5ons ventures private limited,0.876923,0.404255,0.425532,0.2,True
87,S1-318373630,S2-598596199,red ventures private limited,grn chrotre ventures private limited,0.876923,0.293906,0.316832,0.0,True
88,S1-318373630,S2-274887107,red ventures private limited,tirumala sons ventures private limited,0.876923,0.389344,0.409836,0.0,True
83,S1-318373630,S2-803100423,red ventures private limited,rai sons ventures private limited,0.876923,0.374101,0.350365,0.0,True
82,S1-318373630,S2-607679396,red ventures private limited,amritsar ventures private limited,0.876923,0.375159,0.394904,0.0,True
81,S1-318373630,S2-387269711,red ventures private limited,ntx ventures private limited partners,0.876923,0.503597,0.446043,0.0,True
96,S1-318373630,S3-962806873,red ventures private limited,ventures shell support private limited,0.876923,0.420000,0.336634,0.0,True

In [25]:
def build_pair_features(df):
    df = df.copy()

    # -----------------------------
    # Name similarity
    # -----------------------------

    df["rf_ratio"] = df.apply(
        lambda x: fuzz.ratio(
            x["s1_name"],
            x["matched_name"]
        ) / 100,
        axis=1
    )

    df["rf_partial"] = df.apply(
        lambda x: fuzz.partial_ratio(
            x["s1_name"],
            x["matched_name"]
        ) / 100,
        axis=1
    )

    df["rf_token_sort"] = df.apply(
        lambda x: fuzz.token_sort_ratio(
            x["s1_name"],
            x["matched_name"]
        ) / 100,
        axis=1
    )

    df["rf_token_set"] = df.apply(
        lambda x: fuzz.token_set_ratio(
            x["s1_name"],
            x["matched_name"]
        ) / 100,
        axis=1
    )

    df["rf_wratio"] = df.apply(
        lambda x: fuzz.WRatio(
            x["s1_name"],
            x["matched_name"]
        ) / 100,
        axis=1
    )

    # -----------------------------
    # Address similarity
    # -----------------------------

    df["rf_addr_ratio"] = df.apply(
        lambda x: fuzz.ratio(
            x["s1_address"],
            x["matched_address"]
        ) / 100,
        axis=1
    )

    df["rf_addr_partial"] = df.apply(
        lambda x: fuzz.partial_ratio(
            x["s1_address"],
            x["matched_address"]
        ) / 100,
        axis=1
    )

    df["rf_addr_token_sort"] = df.apply(
        lambda x: fuzz.token_sort_ratio(
            x["s1_address"],
            x["matched_address"]
        ) / 100,
        axis=1
    )

    df["rf_addr_token_set"] = df.apply(
        lambda x: fuzz.token_set_ratio(
            x["s1_address"],
            x["matched_address"]
        ) / 100,
        axis=1
    )

    df["rf_addr_wratio"] = df.apply(
        lambda x: fuzz.WRatio(
            x["s1_address"],
            x["matched_address"]
        ) / 100,
        axis=1
    )

    # -----------------------------
    # Exact matches
    # -----------------------------

    df["name_exact"] = (
        df["s1_name"] == df["matched_name"]
    ).astype(int)

    df["address_exact"] = (
        df["s1_address"] == df["matched_address"]
    ).astype(int)

    # -----------------------------
    # Numeric overlap
    # -----------------------------

    df["address_number_overlap"] = df.apply(
        lambda x: number_overlap(
            x["s1_address"],
            x["matched_address"]
        ),
        axis=1
    )

    # -----------------------------
    # Country
    # -----------------------------

    df["country_match"] = (
        df["country_match"].astype(int)
    )

    return df

In [26]:
# Combine our positive and negative pairs

positive_pairs = comparison.copy()

random_negative_pairs = random_negatives.copy()

hard_negative_pairs = hard_negative_clean.copy()

training_pairs = pd.concat(
    [
        positive_pairs,
        random_negative_pairs,
        hard_negative_pairs
    ],
    ignore_index=True
)

print("Total training pairs:", len(training_pairs))
print("Positive pairs:", sum(training_pairs["label"] == 1))
print("Negative pairs:", sum(training_pairs["label"] == 0))

NameError: name 'comparison' is not defined

In [27]:
# Recreate the 70 known-positive S1-S2/S3 pairs

# First retrieve the 70 matched S2/S3 records from the full training files
s2_target_ids = {
    x for x in matched_ids
    if x.startswith("S2-")
}

s3_target_ids = {
    x for x in matched_ids
    if x.startswith("S3-")
}

s2_matches = []

for chunk in pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):
    found = chunk[
        chunk["entity_id"].isin(s2_target_ids)
    ]

    if not found.empty:
        s2_matches.append(found)

s2_gt = pd.concat(
    s2_matches,
    ignore_index=True
)


s3_matches = []

for chunk in pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=100000
):
    found = chunk[
        chunk["entity_id"].isin(s3_target_ids)
    ]

    if not found.empty:
        s3_matches.append(found)

s3_gt = pd.concat(
    s3_matches,
    ignore_index=True
)


# Normalize the retrieved records
for df in [s2_gt, s3_gt]:

    df["business_name_norm"] = (
        df["business_name"].map(normalize_text)
    )

    df["business_address_norm"] = (
        df["business_address"].map(normalize_text)
    )

    df["country_norm"] = (
        df["country"].map(normalize_text)
    )

    df["business_name_core"] = (
        df["business_name_norm"].map(remove_legal_suffix)
    )


# Create lookup for S1
s1_lookup = (
    s1_labeled
    .set_index("entity_id")
    .to_dict("index")
)


rows = []

for _, gt_row in ground_truth.iterrows():

    s1_id = gt_row["source1_entity_id"]

    if s1_id not in s1_lookup:
        continue

    s1_record = s1_lookup[s1_id]

    for matched_id in gt_row["matched_entity_ids"].split(","):

        matched_id = matched_id.strip()

        if matched_id.startswith("S2-"):
            source_df = s2_gt

        elif matched_id.startswith("S3-"):
            source_df = s3_gt

        else:
            continue

        matched = source_df[
            source_df["entity_id"] == matched_id
        ]

        if matched.empty:
            continue

        matched = matched.iloc[0]

        rows.append({
            "s1_id": s1_id,
            "matched_id": matched_id,

            "s1_name": s1_record["business_name_norm"],
            "matched_name": matched["business_name_norm"],

            "s1_core": s1_record["business_name_core"],
            "matched_core": matched["business_name_core"],

            "s1_address": s1_record["business_address_norm"],
            "matched_address": matched["business_address_norm"],

            "country_match": (
                s1_record["country_norm"]
                == matched["country_norm"]
            ),

            "label": 1
        })


comparison = pd.DataFrame(rows)

print("Positive pairs recreated:", len(comparison))
print("Unique S1 entities:", comparison["s1_id"].nunique())
print("Unique matched IDs:", comparison["matched_id"].nunique())

Positive pairs recreated: 70
Unique S1 entities: 20
Unique matched IDs: 70

In [28]:
# Combine positive and negative pairs

positive_pairs = comparison.copy()
random_negative_pairs = random_negatives.copy()
hard_negative_pairs = hard_negative_clean.copy()

training_pairs = pd.concat(
    [
        positive_pairs,
        random_negative_pairs,
        hard_negative_pairs
    ],
    ignore_index=True
)

print("Total pairs:", len(training_pairs))
print("Positive pairs:", (training_pairs["label"] == 1).sum())
print("Negative pairs:", (training_pairs["label"] == 0).sum())

print("\nLabel distribution:")
print(training_pairs["label"].value_counts())

NameError: name 'random_negatives' is not defined

In [29]:
import random

random.seed(42)

negative_rows = []

NEGATIVES_PER_S1 = 20

for _, s1_row in s1_labeled.iterrows():

    # -----------------------------
    # Random S2 negatives
    # -----------------------------
    s2_sample = s2_candidates.sample(
        n=NEGATIVES_PER_S1,
        random_state=42
    )

    for _, s2_row in s2_sample.iterrows():

        negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": s2_row["entity_id"],

            "s1_name": s1_row["business_name_norm"],
            "matched_name": s2_row["business_name_norm"],

            "s1_core": s1_row["business_name_core"],
            "matched_core": s2_row["business_name_core"],

            "s1_address": s1_row["business_address_norm"],
            "matched_address": s2_row["business_address_norm"],

            "country_match": (
                s1_row["country_norm"]
                == s2_row["country_norm"]
            ),

            "label": 0
        })

    # -----------------------------
    # Random S3 negatives
    # -----------------------------
    s3_sample = s3_candidates.sample(
        n=NEGATIVES_PER_S1,
        random_state=42
    )

    for _, s3_row in s3_sample.iterrows():

        negative_rows.append({
            "s1_id": s1_row["entity_id"],
            "matched_id": s3_row["entity_id"],

            "s1_name": s1_row["business_name_norm"],
            "matched_name": s3_row["business_name_norm"],

            "s1_core": s1_row["business_name_core"],
            "matched_core": s3_row["business_name_core"],

            "s1_address": s1_row["business_address_norm"],
            "matched_address": s3_row["business_address_norm"],

            "country_match": (
                s1_row["country_norm"]
                == s3_row["country_norm"]
            ),

            "label": 0
        })

random_negatives = pd.DataFrame(negative_rows)

print("Random negative pairs:", len(random_negatives))
print(
    "S2 negatives:",
    random_negatives["matched_id"]
    .str.startswith("S2-")
    .sum()
)
print(
    "S3 negatives:",
    random_negatives["matched_id"]
    .str.startswith("S3-")
    .sum()
)

Random negative pairs: 800
S2 negatives: 400
S3 negatives: 400

In [30]:
print("comparison:", len(comparison))
print("random_negatives:", len(random_negatives))
print("hard_negative_clean:", len(hard_negative_clean))

print("\nExpected:")
print("comparison = 70")
print("random_negatives = 800")
print("hard_negative_clean = 356")

comparison: 70
random_negatives: 800
hard_negative_clean: 356

Expected:
comparison = 70
random_negatives = 800
hard_negative_clean = 356

In [31]:
positive_pairs = comparison.copy()
random_negative_pairs = random_negatives.copy()
hard_negative_pairs = hard_negative_clean.copy()

training_pairs = pd.concat(
    [positive_pairs, random_negative_pairs, hard_negative_pairs],
    ignore_index=True
)

print("Total training pairs:", len(training_pairs))
print("Positive pairs:", (training_pairs["label"] == 1).sum())
print("Negative pairs:", (training_pairs["label"] == 0).sum())

Total training pairs: 1226
Positive pairs: 70
Negative pairs: 1156

In [32]:
training_features = build_pair_features(training_pairs)

print("Shape:", training_features.shape)

print("\nFeature columns:")
print([
    col for col in training_features.columns
    if col not in [
        "s1_id", "matched_id",
        "s1_name", "matched_name",
        "s1_core", "matched_core",
        "s1_address", "matched_address"
    ]
])

print("\nMissing values:")
print(training_features.isna().sum().sum())

print("\nLabel distribution:")
print(training_features["label"].value_counts())

Shape: (1226, 24)

Feature columns:
['country_match', 'label', 'name_score', 'rf_addr_ratio', 'rf_addr_partial', 'rf_addr_token_sort', 'rf_addr_token_set', 'rf_addr_wratio', 'address_number_overlap', 'rf_ratio', 'rf_partial', 'rf_token_sort', 'rf_token_set', 'rf_wratio', 'name_exact', 'address_exact']

Missing values:
870

Label distribution:
label
0    1156
1      70
Name: count, dtype: int64

In [33]:
# Remove the accidentally inherited hard-negative-only feature
training_features = training_features.drop(columns=["name_score"])

print("New shape:", training_features.shape)

print("\nMissing values:")
print(training_features.isna().sum().sum())

print("\nColumns:")
print(training_features.columns.tolist())

New shape: (1226, 23)

Missing values:
0

Columns:
['s1_id', 'matched_id', 's1_name', 'matched_name', 's1_core', 'matched_core', 's1_address', 'matched_address', 'country_match', 'label', 'rf_addr_ratio', 'rf_addr_partial', 'rf_addr_token_sort', 'rf_addr_token_set', 'rf_addr_wratio', 'address_number_overlap', 'rf_ratio', 'rf_partial', 'rf_token_sort', 'rf_token_set', 'rf_wratio', 'name_exact', 'address_exact']

In [34]:
feature_columns = [
    "country_match",
    "rf_addr_ratio",
    "rf_addr_partial",
    "rf_addr_token_sort",
    "rf_addr_token_set",
    "rf_addr_wratio",
    "address_number_overlap",
    "rf_ratio",
    "rf_partial",
    "rf_token_sort",
    "rf_token_set",
    "rf_wratio",
    "name_exact",
    "address_exact"
]

X = training_features[feature_columns]
y = training_features["label"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nData types:")
print(X.dtypes)

X shape: (1226, 14)
y shape: (1226,)

Features:
['country_match', 'rf_addr_ratio', 'rf_addr_partial', 'rf_addr_token_sort', 'rf_addr_token_set', 'rf_addr_wratio', 'address_number_overlap', 'rf_ratio', 'rf_partial', 'rf_token_sort', 'rf_token_set', 'rf_wratio', 'name_exact', 'address_exact']

Data types:
country_match               int64
rf_addr_ratio             float64
rf_addr_partial           float64
rf_addr_token_sort        float64
rf_addr_token_set         float64
rf_addr_wratio            float64
address_number_overlap    float64
rf_ratio                  float64
rf_partial                float64
rf_token_sort             float64
rf_token_set              float64
rf_wratio                 float64
name_exact                  int64
address_exact               int64
dtype: object

In [35]:
print("Positive matches:", y.sum())
print("Negative matches:", (y == 0).sum())

print("\nPositive percentage:", round(y.mean() * 100, 2), "%")
print("Negative percentage:", round((1 - y.mean()) * 100, 2), "%")

Positive matches: 70
Negative matches: 1156

Positive percentage: 5.71 %
Negative percentage: 94.29 %

In [36]:
from sklearn.model_selection import GroupShuffleSplit

groups = training_features["s1_id"]

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, val_idx = next(
    splitter.split(X, y, groups=groups)
)

X_train = X.iloc[train_idx].copy()
X_val = X.iloc[val_idx].copy()

y_train = y.iloc[train_idx].copy()
y_val = y.iloc[val_idx].copy()

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))

print("\nTraining positives:", y_train.sum())
print("Training negatives:", (y_train == 0).sum())

print("\nValidation positives:", y_val.sum())
print("Validation negatives:", (y_val == 0).sum())

print("\nUnique S1 entities:")
print("Training:", training_features.iloc[train_idx]["s1_id"].nunique())
print("Validation:", training_features.iloc[val_idx]["s1_id"].nunique())

Training samples: 983
Validation samples: 243

Training positives: 56
Training negatives: 927

Validation positives: 14
Validation negatives: 229

Unique S1 entities:
Training: 16
Validation: 4

In [37]:
try:
    import lightgbm as lgb
    print("LightGBM version:", lgb.__version__)
    print("LightGBM is ready.")
except ImportError:
    print("LightGBM is NOT installed.")

LightGBM version: 4.6.0
LightGBM is ready.

In [38]:
import lightgbm as lgb

model = lgb.LGBMClassifier(
    objective="binary",
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

model.fit(
    X_train,
    y_train
)

print("Model training complete.")

Model training complete.

In [39]:
val_probabilities = model.predict_proba(X_val)[:, 1]

print("Number of validation predictions:", len(val_probabilities))

print("\nFirst 20 probabilities:")
print(val_probabilities[:20])

print("\nProbability range:")
print("Minimum:", val_probabilities.min())
print("Maximum:", val_probabilities.max())
print("Mean:", val_probabilities.mean())

Number of validation predictions: 243

First 20 probabilities:
[9.99969341e-01 9.99980549e-01 9.99968973e-01 9.99986139e-01
 9.99970347e-01 9.99966174e-01 9.99886849e-01 8.94274031e-03
 9.99419996e-01 1.49125177e-03 9.99983220e-01 1.47705151e-03
 9.99970546e-01 9.99984015e-01 3.59277463e-08 3.72602978e-08
 6.26946157e-08 3.92549859e-08 1.07717546e-07 6.34295816e-08]

Probability range:
Minimum: 2.7365368426181685e-08
Maximum: 0.9999861389175488
Mean: 0.04532593464543501

In [40]:
from sklearn.metrics import precision_score, recall_score, fbeta_score, confusion_matrix

val_pred_05 = (val_probabilities >= 0.5).astype(int)

precision = precision_score(y_val, val_pred_05, zero_division=0)
recall = recall_score(y_val, val_pred_05, zero_division=0)
f05 = fbeta_score(y_val, val_pred_05, beta=0.5, zero_division=0)

print("Threshold: 0.50")
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F0.5:", round(f05, 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_val, val_pred_05))

Threshold: 0.50
Precision: 1.0
Recall: 0.7857
F0.5: 0.9483

Confusion matrix:
[[229   0]
 [  3  11]]

In [41]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, fbeta_score

threshold_results = []

for threshold in np.arange(0.10, 1.00, 0.05):
    predictions = (val_probabilities >= threshold).astype(int)

    precision = precision_score(
        y_val, predictions, zero_division=0
    )
    recall = recall_score(
        y_val, predictions, zero_division=0
    )
    f05 = fbeta_score(
        y_val, predictions, beta=0.5, zero_division=0
    )

    threshold_results.append({
        "threshold": round(threshold, 2),
        "precision": precision,
        "recall": recall,
        "f0.5": f05,
        "predicted_matches": predictions.sum()
    })

threshold_results = pd.DataFrame(threshold_results)

print(threshold_results.to_string(index=False))

 threshold  precision   recall     f0.5  predicted_matches
      0.10        1.0 0.785714 0.948276                 11
      0.15        1.0 0.785714 0.948276                 11
      0.20        1.0 0.785714 0.948276                 11
      0.25        1.0 0.785714 0.948276                 11
      0.30        1.0 0.785714 0.948276                 11
      0.35        1.0 0.785714 0.948276                 11
      0.40        1.0 0.785714 0.948276                 11
      0.45        1.0 0.785714 0.948276                 11
      0.50        1.0 0.785714 0.948276                 11
      0.55        1.0 0.785714 0.948276                 11
      0.60        1.0 0.785714 0.948276                 11
      0.65        1.0 0.785714 0.948276                 11
      0.70        1.0 0.785714 0.948276                 11
      0.75        1.0 0.785714 0.948276                 11
      0.80        1.0 0.785714 0.948276                 11
      0.85        1.0 0.785714 0.948276                 11
      0.90        1.0 0.785714 0.948276                 11
      0.95        1.0 0.785714 0.948276                 11

In [42]:
val_results = training_features.iloc[val_idx].copy()

val_results["predicted_probability"] = val_probabilities
val_results["prediction"] = (val_probabilities >= 0.5).astype(int)

false_negatives = val_results[
    (val_results["label"] == 1) &
    (val_results["prediction"] == 0)
].copy()

print("False negatives:", len(false_negatives))

print(
    false_negatives[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "country_match",
            "rf_ratio",
            "rf_token_set",
            "rf_wratio",
            "rf_addr_wratio",
            "address_number_overlap",
            "predicted_probability"
        ]
    ].to_string(index=False)
)

False negatives: 3
       s1_id   matched_id                   s1_name                         matched_name                                                                                               s1_address                                                 matched_address  country_match  rf_ratio  rf_token_set  rf_wratio  rf_addr_wratio  address_number_overlap  predicted_probability
S1-789009573  S3-74481402 hotel enterprises limited               hotel limited services wz 187c shop no 13 14 kh no 47 s f vikaspuri budhela village behind oxford school delhi west delhi delhi block b 517 wz 187c shop no 13 divreportingcircle west delhi dl              1  0.553191      0.808511   0.768085           0.855                     0.4               0.008943
S1-730934468 S2-356983532  orellana investments llc orellana investments investments llc                                                             728 a quail avenue fl ground floor geneva ia                                                                              1  0.800000      1.000000   0.855000           0.000                     0.0               0.001491
S1-145361722 S2-120366543 dick regional armada corp                        dick regional                                                                      33466 warwick hills road yucaipa ca                                                                              1  0.684211      1.000000   0.900000           0.000                     0.0               0.001477

In [43]:
positive_train = training_features.iloc[train_idx].copy()

positive_train = positive_train[
    positive_train["label"] == 1
].copy()

print("Positive training examples:", len(positive_train))

print(
    positive_train[
        [
            "s1_name",
            "matched_name",
            "country_match",
            "rf_ratio",
            "rf_partial",
            "rf_token_sort",
            "rf_token_set",
            "rf_wratio",
            "rf_addr_ratio",
            "rf_addr_partial",
            "rf_addr_token_sort",
            "rf_addr_token_set",
            "rf_addr_wratio",
            "address_number_overlap",
            "name_exact",
            "address_exact"
        ]
    ].to_string(index=False)
)

Positive training examples: 56
                                 s1_name                          matched_name  country_match  rf_ratio  rf_partial  rf_token_sort  rf_token_set  rf_wratio  rf_addr_ratio  rf_addr_partial  rf_addr_token_sort  rf_addr_token_set  rf_addr_wratio  address_number_overlap  name_exact  address_exact
            maure williams colombier inc          maure wilblims colombier inc              1  0.964286    0.964286       0.964286      0.964286   0.964286       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           0              0
            maure williams colombier inc              maure williams colombier              1  0.923077    1.000000       0.923077      1.000000   0.950000       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           0              0
            maure williams colombier inc                               dréxkor              1  0.171429    0.285714       0.114286      0.114286   0.257143       0.763158         0.931034            0.736842           0.823529        0.855000                1.000000           0              0
            maure williams colombier inc            maurewilliamscolombier com              1  0.888889    0.901961       0.629630      0.629630   0.888889       0.685714         0.846154            0.657143           0.742857        0.705714                0.000000           0              0
            maure williams colombier inc             maure williams inc center              1  0.679245    0.780488       0.830189      0.837209   0.795349       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           0              0
                     raj investments llp          ர ஜ இன வ ஸ ட ம ண ட ஸ எல எல ப              1  0.085106    0.173913       0.085106      0.100000   0.095000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                     raj investments llp                   raj investments llp              1  1.000000    1.000000       1.000000      1.000000   1.000000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           1              1
                     raj investments llp               raj investments எல எல ப              1  0.761905    0.914286       0.714286      0.882353   0.838235       0.927273         0.990099            0.909091           0.969697        0.927273                1.000000           0              0
                     raj investments llp          ர ஜ இன வ ஸ ட ம ண ட ஸ எல எல ப              1  0.085106    0.173913       0.085106      0.100000   0.095000       0.862069         0.924528            0.844828           0.914286        0.868571                1.000000           0              0
    dahlia power reliable scientific llc                 dahlia power reliable              1  0.736842    1.000000       0.736842      1.000000   0.900000       0.477612         0.622222            0.865672           0.912281        0.866667                1.000000           0              0
    dahlia power reliable scientific llc      dahlia power reliable scientific              1  0.941176    1.000000       0.941176      1.000000   0.950000       0.793651         0.779661            0.793651           0.830189        0.793651                0.500000           0              0
    dahlia power reliable scientific llc   dahlia ponr reliable scientific llc              1  0.957746    0.942857       0.957746      0.957746   0.957746       0.823529         0.949153            0.911765           0.949153        0.901695                1.000000           0              0
                 ss food private limited             एसएस फ ड प र इव ट ल म ट ड              1  0.125000    0.206897       0.125000      0.136364   0.129545       0.767442         0.855263            0.848837           0.883117        0.838961                0.500000           0              0
                 ss food private limited             एसएस फ ड प र इव ट ल म ट ड              1  0.125000    0.206897       0.125000      0.136364   0.129545       0.400000         0.545455            0.608000           0.931507        0.855000                0.250000           0              0
                 ss food private limited             एसएस फ ड प र इव ट ल म ट ड              1  0.125000    0.206897       0.125000      0.136364   0.129545       0.361905         0.684211            0.342857           0.914286        0.855000                0.333333           0              0
                             lumay boral                       lumay boral inc              1  0.846154    1.000000       0.846154      1.000000   0.950000       0.705882         0.716981            0.705882           0.851064        0.855000                0.333333           0              0
                             lumay boral                           lumay bóral              1  0.909091    0.909091       0.909091      0.909091   0.909091       0.867925         0.846154            0.867925           0.867925        0.867925                1.000000           0              0
                             lumay boral                           lumay boral              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.867925         0.846154            0.867925           0.867925        0.867925                1.000000           1              0
                             lumay boral                           lumay bóral              1  0.909091    0.909091       0.909091      0.909091   0.909091       0.928571         0.962963            0.928571           0.928571        0.928571                1.000000           0              0
            red ventures private limited           र ड व चर स प र इव ट ल म ट ड              1  0.109091    0.125000       0.109091      0.122449   0.116327       0.428571         0.551724            0.591837           1.000000        0.855000                0.500000           0              0
            red ventures private limited                  red ventures private              1  0.833333    1.000000       0.833333      1.000000   0.950000       0.626667         0.720000            0.746667           0.859504        0.816529                0.666667           0              0
laxmi golden investments private limited laxmi gbn lnvestments private limited              1  0.909091    0.864865       0.623377      0.909091   0.909091       0.919643         0.958140            0.910714           0.949495        0.919643                1.000000           0              0
laxmi golden investments private limited              laxmi golden investments              1  0.750000    1.000000       0.750000      1.000000   0.900000       0.958904         0.990566            0.958904           0.949495        0.958904                1.000000           0              0
               hendricks and flowers inc             hendricks and flowers inc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.888889         0.933333            0.952381           1.000000        0.950000                0.000000           1              0
               hendricks and flowers inc             hendricks and inc flowers              1  0.840000    0.913043       1.000000      1.000000   0.950000       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           0              0
                        chordia partners              chordia partners company              1  0.800000    1.000000       0.800000      1.000000   0.900000       0.622951         0.730769            0.754098           0.867925        0.824528                1.000000           0              0
                        chordia partners           chordia pagnters 7306204978              1  0.651163    0.875000       0.651163      0.651163   0.855000       0.579710         0.690909            0.724638           0.851852        0.809259                1.000000           0              0
                        chordia partners                  chordia pártners ltd              1  0.833333    0.937500       0.833333      0.833333   0.833333       0.666667         0.709677            0.909091           0.909091        0.863636                1.000000           0              0
                        chordia partners                    smt chordia center              1  0.647059    0.733333       0.529412      0.705882   0.670588       0.590164         0.705882            0.754098           0.867925        0.824528                1.000000           0              0
          crystal staffing solutions llc        crystal solutions llc partners              1  0.700000    0.823529       0.700000      0.823529   0.782353       0.955224         0.906250            0.955224           0.955224        0.955224                1.000000           0              0
          crystal staffing solutions llc      crystal staffing solutions l l c              1  0.967742    0.966667       0.935484      0.933333   0.967742       0.955224         0.906250            0.955224           0.955224        0.955224                1.000000           0              0
          crystal staffing solutions llc       llc crystal sttfrifng solutions              1  0.786885    0.842105       0.918033      0.918033   0.872131       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
          crystal staffing solutions llc        llc crystal staffing solutions              1  0.866667    0.928571       1.000000      1.000000   0.950000       0.839506         0.970588            0.814815           0.870968        0.839506                0.000000           0              0
          crystal staffing solutions llc        llc crystal shaffing solutions              1  0.833333    0.892857       0.700000      0.966667   0.918333       0.839506         0.970588            0.814815           0.870968        0.839506                0.000000           0              0
          crystal staffing solutions llc                               crystal              1  0.378378    1.000000       0.378378      1.000000   0.900000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                            obsidian llc                          obsidian llc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.892308         0.931034            0.892308           0.912281        0.892308                1.000000           1              0
                            obsidian llc                          obsidian llc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           1              0
                            obsidian llc                   obsidian llc center              1  0.774194    1.000000       0.774194      1.000000   0.900000       0.892308         0.931034            0.892308           0.912281        0.892308                1.000000           0              0
                            obsidian llc                          obsidian llc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.380952         0.558140            0.761905           0.761905        0.723810                0.000000           1              0
                            obsidian llc                          obsidian llc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.000000         0.000000            0.000000           0.000000        0.000000                0.000000           1              0
                            obsidian llc           korbrixx d b a obsidian llc              1  0.615385    1.000000       0.615385      1.000000   0.900000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                      ap hospitality inc                  ap inc service 80430              1  0.368421    0.500000       0.368421      0.500000   0.475000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                      ap hospitality inc                    ap hospitality ínc              1  0.944444    0.944444       0.944444      0.944444   0.944444       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                      ap hospitality inc                    ap inc hospitality              1  0.777778    0.875000       1.000000      1.000000   0.950000       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                      ap hospitality inc                         ap ínc center              1  0.322581    0.375000       0.451613      0.451613   0.429032       1.000000         1.000000            1.000000           1.000000        1.000000                1.000000           0              1
                      ap hospitality inc                    inc ap hospitality              1  0.777778    0.875000       1.000000      1.000000   0.950000       0.866667         0.961538            0.866667           0.938776        0.891837                0.666667           0              0
                      ap hospitality inc                    ap hospitality inc              1  1.000000    1.000000       1.000000      1.000000   1.000000       0.866667         0.961538            0.866667           0.938776        0.891837                0.666667           1              0
                      ap hospitality inc        ap ap hospitality incorporated              1  0.750000    1.000000       0.750000      0.875000   0.900000       0.866667         0.961538            0.866667           0.938776        0.891837                0.666667           0              0
                     desai alanah esq pc                      desai alanah esq              1  0.914286    1.000000       0.914286      1.000000   0.950000       0.761905         0.651163            0.761905           0.780488        0.855000                0.000000           0              0
                     desai alanah esq pc                      desai alanah ésq              1  0.857143    0.937500       0.857143      0.857143   0.857143       0.727273         0.848485            0.727273           0.793651        0.753968                0.500000           0              0
       balaji investment private limited    బ ల జ ఇన వ స ట మ ట ప ర వ ట ల మ ట డ              1  0.089552    0.153846       0.089552      0.109091   0.103636       0.626087         0.692308            0.904348           1.000000        0.950000                0.666667           0              0
       balaji investment private limited     balaji insvstemnt private limited              1  0.939394    0.939394       0.939394      0.939394   0.939394       0.659091         0.800000            0.590909           0.716981        0.681132                1.000000           0              0
                              uptown pub                         uptown pub co              1  0.869565    1.000000       0.869565      1.000000   0.950000       0.941176         0.941176            0.941176           0.941176        0.941176                1.000000           0              0
                              uptown pub                            solkeloquo              1  0.200000    0.333333       0.200000      0.200000   0.200000       0.783784         0.878788            0.702703           0.729730        0.783784                0.500000           0              0
                       prem sons pvt ltd                 prem pvt ltd services              1  0.631579    0.827586       0.789474      0.827586   0.786207       0.907407         0.914894            0.907407           1.000000        0.950000                1.000000           0              0
                       prem sons pvt ltd                 prem pvt ltd partners              1  0.631579    0.827586       0.631579      0.827586   0.786207       0.426667         0.875000            0.426667           0.896552        0.855000                0.500000           0              0

In [44]:
feature_importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

print(feature_importance.to_string(index=False))

               feature  importance
         rf_token_sort         755
       rf_addr_partial         694
     rf_addr_token_set         674
         rf_addr_ratio         669
        rf_addr_wratio         520
              rf_ratio         515
            rf_partial         396
    rf_addr_token_sort         386
          rf_token_set         374
             rf_wratio         287
address_number_overlap          47
         country_match          18
            name_exact           0
         address_exact           0

In [45]:
weighted_model = lgb.LGBMClassifier(
    objective="binary",
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

weighted_model.fit(
    X_train,
    y_train
)

print("Class-weighted model training complete.")

Class-weighted model training complete.

In [46]:
weighted_val_probabilities = weighted_model.predict_proba(X_val)[:, 1]

weighted_val_pred = (
    weighted_val_probabilities >= 0.5
).astype(int)

weighted_precision = precision_score(
    y_val,
    weighted_val_pred,
    zero_division=0
)

weighted_recall = recall_score(
    y_val,
    weighted_val_pred,
    zero_division=0
)

weighted_f05 = fbeta_score(
    y_val,
    weighted_val_pred,
    beta=0.5,
    zero_division=0
)

print("Class-weighted model")
print("--------------------")
print("Precision:", round(weighted_precision, 4))
print("Recall:", round(weighted_recall, 4))
print("F0.5:", round(weighted_f05, 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_val, weighted_val_pred))

Class-weighted model
--------------------
Precision: 1.0
Recall: 0.7857
F0.5: 0.9483

Confusion matrix:
[[229   0]
 [  3  11]]

In [47]:
from sklearn.metrics import roc_auc_score, average_precision_score

roc_auc = roc_auc_score(
    y_val,
    val_probabilities
)

pr_auc = average_precision_score(
    y_val,
    val_probabilities
)

print("ROC-AUC:", round(roc_auc, 4))
print("PR-AUC:", round(pr_auc, 4))

ROC-AUC: 0.9994
PR-AUC: 0.9901

In [48]:
# Load the complete training ground truth
full_ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Full ground truth shape:", full_ground_truth.shape)

print("\nColumns:")
print(full_ground_truth.columns.tolist())

print("\nFirst 5 rows:")
print(full_ground_truth.head())

print("\nUnique S1 entities:")
print(full_ground_truth["source1_entity_id"].nunique())

Full ground truth shape: (2206821, 2)

Columns:
['source1_entity_id', 'matched_entity_ids']

First 5 rows:
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

Unique S1 entities:
2206821

In [49]:
# Count how many S2 and S3 matches each S1 has
full_ground_truth["s2_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S2-")
)

full_ground_truth["s3_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S3-")
)

print("Total S1 entities:", len(full_ground_truth))

print("\nTotal S2 matches:",
      full_ground_truth["s2_count"].sum())

print("Total S3 matches:",
      full_ground_truth["s3_count"].sum())

print("Total matches:",
      full_ground_truth["s2_count"].sum()
      + full_ground_truth["s3_count"].sum())

print("\nAverage S2 matches per S1:",
      round(full_ground_truth["s2_count"].mean(), 3))

print("Average S3 matches per S1:",
      round(full_ground_truth["s3_count"].mean(), 3))

print("\nS1 entities with no matches:")
print(
    (
        (full_ground_truth["s2_count"] == 0) &
        (full_ground_truth["s3_count"] == 0)
    ).sum()
)

Total S1 entities: 2206821

Total S2 matches: 3693619
Total S3 matches: 3944746
Total matches: 7638365

Average S2 matches per S1: 1.674
Average S3 matches per S1: 1.788

S1 entities with no matches:
123247

In [50]:
# Sample S1 entities for a larger training experiment

SAMPLE_S1 = 50000

matched_s1 = full_ground_truth[
    (full_ground_truth["s2_count"] > 0) |
    (full_ground_truth["s3_count"] > 0)
].copy()

sampled_s1 = matched_s1.sample(
    n=SAMPLE_S1,
    random_state=42
)

print("Sampled S1 entities:", len(sampled_s1))

print(
    "Expected positive S2 matches:",
    sampled_s1["s2_count"].sum()
)

print(
    "Expected positive S3 matches:",
    sampled_s1["s3_count"].sum()
)

print(
    "Expected total positive pairs:",
    sampled_s1["s2_count"].sum()
    + sampled_s1["s3_count"].sum()
)

Sampled S1 entities: 50000
Expected positive S2 matches: 88440
Expected positive S3 matches: 94744
Expected total positive pairs: 183184

In [52]:
# Extract the known positive entity IDs for our 50k sampled S1 entities

sampled_s2_ids = set()
sampled_s3_ids = set()

for matched_ids in sampled_s1["matched_entity_ids"]:
    if not matched_ids:
        continue

    for entity_id in matched_ids.split(","):
        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            sampled_s2_ids.add(entity_id)

        elif entity_id.startswith("S3-"):
            sampled_s3_ids.add(entity_id)

print("Unique S2 positive IDs:", len(sampled_s2_ids))
print("Unique S3 positive IDs:", len(sampled_s3_ids))

Unique S2 positive IDs: 88440
Unique S3 positive IDs: 94744

In [53]:
def load_selected_records(file_path, selected_ids, chunk_size=200_000):
    selected_parts = []

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        keep_default_na=False,
        chunksize=chunk_size
    ):
        matched = chunk[chunk["entity_id"].isin(selected_ids)]

        if len(matched) > 0:
            selected_parts.append(matched)

    if selected_parts:
        return pd.concat(selected_parts, ignore_index=True)

    return pd.DataFrame()


sampled_s2 = load_selected_records(
    file_paths["train_source2.tsv"],
    sampled_s2_ids
)

sampled_s3 = load_selected_records(
    file_paths["train_source3.tsv"],
    sampled_s3_ids
)

print("Retrieved S2 records:", len(sampled_s2))
print("Retrieved S3 records:", len(sampled_s3))

print("\nExpected S2:", len(sampled_s2_ids))
print("Expected S3:", len(sampled_s3_ids))

Retrieved S2 records: 88440
Retrieved S3 records: 94744

Expected S2: 88440
Expected S3: 94744

In [54]:
# Convert the comma-separated ground-truth matches into individual rows

positive_mapping = sampled_s1[
    ["source1_entity_id", "matched_entity_ids"]
].copy()

positive_mapping["matched_id"] = (
    positive_mapping["matched_entity_ids"]
    .str.split(",")
)

positive_mapping = positive_mapping.explode(
    "matched_id",
    ignore_index=True
)

positive_mapping["matched_id"] = (
    positive_mapping["matched_id"].str.strip()
)

positive_mapping = positive_mapping.drop(
    columns=["matched_entity_ids"]
)

print("Positive mapping rows:", len(positive_mapping))

print("\nS2 pairs:",
      positive_mapping["matched_id"].str.startswith("S2-").sum())

print("S3 pairs:",
      positive_mapping["matched_id"].str.startswith("S3-").sum())

print("\nFirst 5 rows:")
print(positive_mapping.head())

Positive mapping rows: 183184

S2 pairs: 88440
S3 pairs: 94744

First 5 rows:
  source1_entity_id    matched_id
0      S1-777210964   S2-12029274
1      S1-777210964  S2-407524980
2      S1-777210964  S3-970714334
3      S1-777210964  S3-712922821
4      S1-190133982  S2-523219173

In [55]:
sampled_s1_ids = set(
    sampled_s1["source1_entity_id"]
)

sampled_s1_records = load_selected_records(
    file_paths["train_source1.tsv"],
    sampled_s1_ids
)

print("Retrieved S1 records:", len(sampled_s1_records))
print("Expected S1 records:", len(sampled_s1_ids))

print("\nColumns:")
print(sampled_s1_records.columns.tolist())

Retrieved S1 records: 50000
Expected S1 records: 50000

Columns:
['entity_id', 'business_name', 'business_address', 'country']

In [56]:
# Rename S1 columns so the merge is unambiguous
s1_positive = sampled_s1_records.rename(
    columns={
        "entity_id": "s1_id",
        "business_name": "s1_name",
        "business_address": "s1_address",
        "country": "s1_country"
    }
)

# Combine S2 and S3 into one candidate table
s23_positive = pd.concat(
    [
        sampled_s2.assign(source="S2"),
        sampled_s3.assign(source="S3")
    ],
    ignore_index=True
)

s23_positive = s23_positive.rename(
    columns={
        "entity_id": "matched_id",
        "business_name": "matched_name",
        "business_address": "matched_address",
        "country": "matched_country"
    }
)

# Merge S1 information
positive_pairs_full = positive_mapping.merge(
    s1_positive,
    left_on="source1_entity_id",
    right_on="s1_id",
    how="left"
)

# Merge matched S2/S3 information
positive_pairs_full = positive_pairs_full.merge(
    s23_positive[
        [
            "matched_id",
            "matched_name",
            "matched_address",
            "matched_country"
        ]
    ],
    on="matched_id",
    how="left"
)

# Country agreement
positive_pairs_full["country_match"] = (
    positive_pairs_full["s1_country"]
    == positive_pairs_full["matched_country"]
).astype(int)

print("Positive pairs:", len(positive_pairs_full))

print("\nMissing S1 names:",
      positive_pairs_full["s1_name"].isna().sum())

print("Missing matched names:",
      positive_pairs_full["matched_name"].isna().sum())

print("Missing S1 addresses:",
      positive_pairs_full["s1_address"].isna().sum())

print("Missing matched addresses:",
      positive_pairs_full["matched_address"].isna().sum())

print("\nFirst 5 rows:")
print(
    positive_pairs_full[
        [
            "s1_id",
            "matched_id",
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "country_match"
        ]
    ].head().to_string(index=False)
)

Positive pairs: 183184

Missing S1 names: 0
Missing matched names: 0
Missing S1 addresses: 0
Missing matched addresses: 0

First 5 rows:
       s1_id   matched_id             s1_name          matched_name                                                                                 s1_address                                                                              matched_address  country_match
S1-777210964  S2-12029274 Davis Family Office    Davis Family Offie                                                               88 Olive Circle, Lebanon, TN                                                                    88 OLIVE CIR, LEBANON, TN              1
S1-777210964 S2-407524980 Davis Family Office   DAVIS FAMILY OFFICE                                                               88 Olive Circle, Lebanon, TN                                                                       OLIVE CIR, LEBANON, TN              1
S1-777210964 S3-970714334 Davis Family Office Davis Family (Office)                                                               88 Olive Circle, Lebanon, TN                                                             88 Olive Cir, Lebanon, Tennessee              1
S1-777210964 S3-712922821 Davis Family Office          Davis Family                                                               88 Olive Circle, Lebanon, TN                                                             Lebanon, Tennessee, 88 Olive Cir              1
S1-190133982 S2-523219173 MS Consultancy Corp      MS [Consultancy] Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra SHYMALA APPTS 1-1ST FLOOR FLAT NO. 4 OPP RATNA HOSPITAL SB ROAD IN HAVELI, PUNE, Maharashtra              1

In [57]:
# Normalize the sampled S1/S2/S3 records

for df in [sampled_s1_records, sampled_s2, sampled_s3]:
    df["name_norm"] = df["business_name"].apply(normalize_text)
    df["address_norm"] = df["business_address"].apply(normalize_text)
    df["name_core"] = df["name_norm"].apply(remove_legal_suffix)

print("S1 normalized:", sampled_s1_records.shape)
print("S2 normalized:", sampled_s2.shape)
print("S3 normalized:", sampled_s3.shape)

print("\nExample:")
print(
    sampled_s1_records[
        ["business_name", "name_norm", "name_core"]
    ].head().to_string(index=False)
)

S1 normalized: (50000, 7)
S2 normalized: (88440, 7)
S3 normalized: (94744, 7)

Example:
                    business_name                         name_norm                name_core
              Orelee's Barbershop               orelee s barbershop      orelee s barbershop
   Foot & Ankle Allied Center LLC      foot ankle allied center llc foot ankle allied center
      Morbi Wires Private Limited       morbi wires private limited              morbi wires
         Sloan Mountain Grid Corp          sloan mountain grid corp      sloan mountain grid
New International Private Limited new international private limited        new international

In [58]:
from collections import defaultdict

# Build exact normalized-name indexes for S2 and S3

s2_name_index = defaultdict(list)
s3_name_index = defaultdict(list)

for entity_id, name in zip(sampled_s2["entity_id"], sampled_s2["name_norm"]):
    if name:
        s2_name_index[name].append(entity_id)

for entity_id, name in zip(sampled_s3["entity_id"], sampled_s3["name_norm"]):
    if name:
        s3_name_index[name].append(entity_id)

print("Unique S2 normalized names:", len(s2_name_index))
print("Unique S3 normalized names:", len(s3_name_index))

print("\nExample S2 index entries:")
for name, ids in list(s2_name_index.items())[:5]:
    print(name, "->", ids[:5])

Unique S2 normalized names: 79913
Unique S3 normalized names: 86317

Example S2 index entries:
division of sanitation -> ['S2-401480583', 'S2-190046947']
highland arc inc -> ['S2-838526909']
the spicewood homes -> ['S2-982496654']
jeanette fisher alliance llc -> ['S2-705827573']
ज न व चर स प र इव ट ल म ट ड -> ['S2-735885703']

In [59]:
# Create normalized-name mappings for the known positive pairs

positive_pairs_full["s1_name_norm"] = (
    positive_pairs_full["s1_name"].apply(normalize_text)
)

positive_pairs_full["matched_name_norm"] = (
    positive_pairs_full["matched_name"].apply(normalize_text)
)

# Exact normalized-name match
positive_pairs_full["exact_name_block"] = (
    positive_pairs_full["s1_name_norm"]
    == positive_pairs_full["matched_name_norm"]
)

coverage = positive_pairs_full["exact_name_block"].mean()

print(f"Exact normalized-name coverage: {coverage:.2%}")
print(
    f"Positive pairs recovered: "
    f"{positive_pairs_full['exact_name_block'].sum():,} / "
    f"{len(positive_pairs_full):,}"
)

print("\nExamples NOT recovered by exact name:")
print(
    positive_pairs_full[
        ~positive_pairs_full["exact_name_block"]
    ][
        [
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

Exact normalized-name coverage: 21.75%
Positive pairs recovered: 39,837 / 183,184

Examples NOT recovered by exact name:
            s1_name          matched_name                                                                                       s1_address                                                                                         matched_address
Davis Family Office    Davis Family Offie                                                                     88 Olive Circle, Lebanon, TN                                                                               88 OLIVE CIR, LEBANON, TN
Davis Family Office          Davis Family                                                                     88 Olive Circle, Lebanon, TN                                                                        Lebanon, Tennessee, 88 Olive Cir
MS Consultancy Corp      MS [Consultancy]       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra            SHYMALA APPTS 1-1ST FLOOR FLAT NO. 4 OPP RATNA HOSPITAL SB ROAD IN HAVELI, PUNE, Maharashtra
MS Consultancy Corp  M5  Consultancy Corp       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra                 Pune, MH, Pune, Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli
MS Consultancy Corp      MS Corp Services       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra                       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, MH
 Team Air Pvt. Ltd.           TEAMAIR.COM Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana                     FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, తెలంగాణ
 Team Air Pvt. Ltd.     Thg Air Pvt. Ltd. Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana                                                                  FLAT NO:101, -POOL, HYDERABAD, తెలంగాణ
 Team Air Pvt. Ltd.           teamair.com Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana                   FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, Telangana
 Team Air Pvt. Ltd.               Mirasol Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana Flat No:1-101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, Hyderabad, -Pool, Andhra Pradesh
 Team Air Pvt. Ltd. Team Air Pvt. Limited Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana Flat No:1-101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Andhra Pradesh

In [60]:
# Add normalized core names to the positive pairs

positive_pairs_full["s1_name_core"] = (
    positive_pairs_full["s1_name_norm"]
    .apply(remove_legal_suffix)
)

positive_pairs_full["matched_name_core"] = (
    positive_pairs_full["matched_name_norm"]
    .apply(remove_legal_suffix)
)

# Exact core-name match
positive_pairs_full["exact_core_block"] = (
    positive_pairs_full["s1_name_core"]
    == positive_pairs_full["matched_name_core"]
)

core_coverage = positive_pairs_full["exact_core_block"].mean()

print(f"Exact core-name coverage: {core_coverage:.2%}")
print(
    f"Positive pairs recovered: "
    f"{positive_pairs_full['exact_core_block'].sum():,} / "
    f"{len(positive_pairs_full):,}"
)

print("\nAdditional pairs recovered by core-name blocking:")
print(
    positive_pairs_full[
        positive_pairs_full["exact_core_block"]
        & ~positive_pairs_full["exact_name_block"]
    ][
        [
            "s1_name",
            "matched_name",
            "s1_name_core",
            "matched_name_core"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

Exact core-name coverage: 36.64%
Positive pairs recovered: 67,115 / 183,184

Additional pairs recovered by core-name blocking:
                      s1_name            matched_name           s1_name_core      matched_name_core
          MS Consultancy Corp        MS [Consultancy]         ms consultancy         ms consultancy
           Team Air Pvt. Ltd.   Team Air Pvt. Limited               team air               team air
        Grand Connecticut LLC       Grand Connecticut      grand connecticut      grand connecticut
        Grand Connecticut LLC       Grand Connecticut      grand connecticut      grand connecticut
          FH Business Pvt Ltd FH BUSINESS PVT LIMITED            fh business            fh business
Unique & Sons Private Limited           Unique & Sons            unique sons            unique sons
           Hotel Food Limited              HOTEL FOOD             hotel food             hotel food
           Lambodar Softwares  Lambodar Softwares Ltd     lambodar softwares     lambodar softwares
    Brit Cash Modern Proem Co  Brit Cash Modern Proem brit cash modern proem brit cash modern proem
          Mountain Center LLC         Mountain Center        mountain center        mountain center

In [61]:
# Extract numeric tokens from normalized addresses

positive_pairs_full["s1_address_numbers"] = (
    positive_pairs_full["s1_address"]
    .apply(extract_numbers)
)

positive_pairs_full["matched_address_numbers"] = (
    positive_pairs_full["matched_address"]
    .apply(extract_numbers)
)

# Check whether the two addresses share at least one number
positive_pairs_full["address_number_block"] = positive_pairs_full.apply(
    lambda x: bool(
        x["s1_address_numbers"]
        & x["matched_address_numbers"]
    ),
    axis=1
)

number_coverage = positive_pairs_full["address_number_block"].mean()

print(f"Address-number coverage: {number_coverage:.2%}")
print(
    f"Positive pairs recovered: "
    f"{positive_pairs_full['address_number_block'].sum():,} / "
    f"{len(positive_pairs_full):,}"
)

print("\nExamples:")
print(
    positive_pairs_full[
        positive_pairs_full["address_number_block"]
    ][
        [
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address",
            "s1_address_numbers",
            "matched_address_numbers"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

Address-number coverage: 79.73%
Positive pairs recovered: 146,046 / 183,184

Examples:
                  s1_name              matched_name                                                                                       s1_address                                                                              matched_address s1_address_numbers matched_address_numbers
      Davis Family Office        Davis Family Offie                                                                     88 Olive Circle, Lebanon, TN                                                                    88 OLIVE CIR, LEBANON, TN               {88}                    {88}
      Davis Family Office     Davis Family (Office)                                                                     88 Olive Circle, Lebanon, TN                                                             88 Olive Cir, Lebanon, Tennessee               {88}                    {88}
      Davis Family Office              Davis Family                                                                     88 Olive Circle, Lebanon, TN                                                             Lebanon, Tennessee, 88 Olive Cir               {88}                    {88}
      MS Consultancy Corp          MS [Consultancy]       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra SHYMALA APPTS 1-1ST FLOOR FLAT NO. 4 OPP RATNA HOSPITAL SB ROAD IN HAVELI, PUNE, Maharashtra             {1, 4}                  {1, 4}
      MS Consultancy Corp      M5  Consultancy Corp       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra      Pune, MH, Pune, Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli             {1, 4}                  {1, 4}
      MS Consultancy Corp          MS Corp Services       Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra            Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, MH             {1, 4}                  {1, 4}
3520 Main Road Realty Inc 3520 MAIN ROAD Realty INC                                                                   TX, 158 Simpson Lane, Somerset                                                            158 Simpson Lane, Somerset, Texas              {158}                   {158}
       Team Air Pvt. Ltd.               TEAMAIR.COM Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana          FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, తెలంగాణ              {101}                   {101}
       Team Air Pvt. Ltd.         Thg Air Pvt. Ltd. Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana                                                       FLAT NO:101, -POOL, HYDERABAD, తెలంగాణ              {101}                   {101}
       Team Air Pvt. Ltd.               teamair.com Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana        FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, Telangana              {101}                   {101}

In [62]:
# Combine our three blocking signals

positive_pairs_full["combined_block"] = (
    positive_pairs_full["exact_name_block"]
    | positive_pairs_full["exact_core_block"]
    | positive_pairs_full["address_number_block"]
)

combined_coverage = positive_pairs_full["combined_block"].mean()

print(f"Combined blocking coverage: {combined_coverage:.2%}")
print(
    f"Positive pairs recovered: "
    f"{positive_pairs_full['combined_block'].sum():,} / "
    f"{len(positive_pairs_full):,}"
)

print(
    f"Positive pairs still missed: "
    f"{(~positive_pairs_full['combined_block']).sum():,}"
)

print("\nExamples still missed by all three:")
print(
    positive_pairs_full[
        ~positive_pairs_full["combined_block"]
    ][
        [
            "s1_name",
            "matched_name",
            "s1_address",
            "matched_address"
        ]
    ]
    .head(15)
    .to_string(index=False)
)

Combined blocking coverage: 87.65%
Positive pairs recovered: 160,568 / 183,184
Positive pairs still missed: 22,616

Examples still missed by all three:
                             s1_name                          matched_name                                                                                s1_address                                 matched_address
       Prairie Capital Partners PLLC                     Prairie (Capital)                                               120 Autumn Woods Boulevard, Mount Holly, NC              AUTUMN WOODS BLVD, MOUNT HOLLY, NC
       Prairie Capital Partners PLLC       Prairie Partners PLLC  Services                                               120 Autumn Woods Boulevard, Mount Holly, NC  Autumn Woods Blvd, Mount Holly, North Carolina
            Mendez's Excavation PLLC                   Mendez's Excavation                                                            914 Charlotte Drive, Anoka, MN                  Charlotte Dr, Anoka, Minnesota
Royal Packaging Corporation Partners                  *** Royal  Packaging                                            PA, 1104 Freedley Street, Conshohocken Borough Freedley St, Conshohocken Borough, Pennsylvania
                  Novyx Networks Inc                    Novyx Inc Services                                          35973 Bushwacker Pass Street, San Tan Valley, AZ          Bushwacker Pass St, SAN TAN VALLEY, AZ
                  Lambodar Softwares                    Lambodar Sfocwares B-702, Shreeji Arcade B/H Bhulkabhavan School, Anand Mahal Roa, D, Adajan, Surat, Gujarat
  Hagaman Economic Development Trust Hagaman Efollntmonc Development Trust                                                            80 Hagaman Avenue, NY, Hagaman                   30 HAGAMAN AVE, AMSTERDAM, NY
  Hagaman Economic Development Trust          HAGAMAN ÉCONOMIC DEVELOPMENT                                                            80 Hagaman Avenue, NY, Hagaman
  Hagaman Economic Development Trust    Hagaman Economic Trust Development                                                            80 Hagaman Avenue, NY, Hagaman                  30 Hagaman Avenue, HAGAMAN, NY
          Family Empire Partners LLC                        Family  Empire                                                             2716 Valdez Drive, Temple, TX                        Valdez Dr, Temple, Texas
Garcia Mountain Biotherapeutics PLLC Garcia Mountain Biootherapeutics PLLC                                                         11171 Samish Island Road, Bow, WA            SAMISH ISLAND RD, null, BOW  CDP, WA
Garcia Mountain Biotherapeutics PLLC       GARCIA MOUNTAIN BIOTHERAPEUTICS                                                         11171 Samish Island Road, Bow, WA       1117 Samish Island Rd, null, BOW  CDP, WA
Garcia Mountain Biotherapeutics PLLC  Garcia Mountain Bíotherapeutics PLLC                                                         11171 Samish Island Road, Bow, WA    011171 Samish Island Rd, BOW CDP, Washington
                     Surgical Health           Surgical Héalth Enterprises                                                Bldg 7, Leominster, MA, 380 Central Street
                     Surgical Health       Surgical Health LP - 2810307279                                                Bldg 7, Leominster, MA, 380 Central Street                00380 CENTRAL ST, LEOMINSTER, MA

In [63]:
from rapidfuzz import fuzz

# Calculate fuzzy name similarity only for the positive pairs
# that our current blocking rules missed.

missed_pairs = positive_pairs_full[
    ~positive_pairs_full["combined_block"]
].copy()

missed_pairs["name_wratio"] = missed_pairs.apply(
    lambda x: fuzz.WRatio(
        x["s1_name_norm"],
        x["matched_name_norm"]
    ) / 100,
    axis=1
)

missed_pairs["name_token_set"] = missed_pairs.apply(
    lambda x: fuzz.token_set_ratio(
        x["s1_name_norm"],
        x["matched_name_norm"]
    ) / 100,
    axis=1
)

print("Missed positive pairs:", len(missed_pairs))

print("\nName WRatio statistics:")
print(
    missed_pairs["name_wratio"].describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nName Token-Set statistics:")
print(
    missed_pairs["name_token_set"].describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
    )
)

print("\nExamples with high fuzzy name similarity:")
print(
    missed_pairs.sort_values(
        "name_wratio",
        ascending=False
    )[
        [
            "s1_name",
            "matched_name",
            "name_wratio",
            "name_token_set",
            "s1_address",
            "matched_address"
        ]
    ]
    .head(20)
    .to_string(index=False)
)

Missed positive pairs: 22616

Name WRatio statistics:
count    22616.000000
mean         0.810304
std          0.240291
min          0.000000
25%          0.812500
50%          0.900000
75%          0.950000
90%          0.952381
95%          0.964286
99%          0.975610
max          0.989691
Name: name_wratio, dtype: float64

Name Token-Set statistics:
count    22616.000000
mean         0.814731
std          0.266866
min          0.000000
25%          0.794784
50%          0.925926
75%          1.000000
90%          1.000000
95%          1.000000
99%          1.000000
max          1.000000
Name: name_token_set, dtype: float64

Examples with high fuzzy name similarity:
                                          s1_name                                     matched_name  name_wratio  name_token_set                                                                                                         s1_address                                                                                         matched_address
Fresh Energy Company of Truth Or Consequences Inc Fresh Energy Company of Truth Or Consequence Inc     0.989691        0.989691                                                                    113 Hillcrest Circle, Truth Or Consequences, NM                                                    111 Hillcrest Cir, Truth Or Consequences, New Mexico
        India Electric Consultancy Public Limited     India Electrlic Consultancy Public [Limited]     0.987952        0.987952                                                                                   Karunj, Maval, Pune, Maharashtra                                                                                Karunj, Pune, महाराष्ट्र
        Builders Janavi Bengaluru Private Limited       Builders Janabvi Bengaluru Private Limited     0.987952        0.987952                                       Dibiyapur, Bypass, Narotampur Auraiya, Uttar Pradesh, Auraiya, Uttar Pradesh                            DIBIYAPUR, BYPASS, NAROTAMPUR AURAIYA, UTTAR PRADESH, AURAIYA, Uttar Pradesh
         Developers Mita Services Private Limited          DEVELOPERS MTA SERVICES PRIVATE LIMITED     0.987342        0.987342                                                                              78/6, Partap Mohalla, Rohtak, Haryana
         Park (India) Expeditions Private Limited          PARK (INDIA) EXPEDITION PRIVATE LIMITED     0.986667        0.986667                 Radha Krishna Flat, Near Sahjanand College, Bank Of Maharashtra Lane, Ambawadi, Ahmedabad, Gujarat                 RADHA KRISHNA FLAT, NEAR SAHJANAND COLLEGE, BANK OF MAHARASHTRA LANE, AMBAWADI, Gujarat
            Opaline Mcgowan Atlantic Textiles Inc             Opaline Mcgwan Atlantic Textiles Inc     0.986301        0.986301                                                                           9279 Ingleside Farm Road, Germantown, TN                                                                     INGLESIDE FARM ROAD, GERMANTOWN, TN
            Agnesse Caldwell American Grifols LLC            AGNESSE  CALDWELL AMERICAN GRIFOL LLC     0.986301        0.986301                                                                                     1040 Austin Avenue, Aurora, IL                                                                           104 AUSTIN AVENUE, AURORA, IL
             Hochstein Allied Family Practice Inc            Hochstein Allied Family Prahctice Inc     0.986301        0.986301                                                                                 NY, 24 Krissa Court, Staten Island
            Chiropractic Heritage Physicians Inc.           Chiropractic Heritage Physbicians Inc.     0.986301        0.986301                                                                                 17006 Oakleigh Way, Hagerstown, MD
            Bangalore North Homes Private Limited             Bangalore North Hoes Private Limited     0.986301        0.986301                            T5, 172, Pebblebay, 1St Main Road Rmv, 2Nd Stage, Bangalore North, Bangalore, Karnataka
            Silver Global Exports Private Limited             SILVER GOBAL EXPORTS PRIVATE LIMITED     0.986301        0.986301                                                  Vinayakar Kovil Streetalandurai Alandurai, Coimbatore, Tamil Nadu
             Shree Dream Infotech Private Limited           Shree Drheam  Infotech Private Limited     0.986301        0.986301 Madyan Nagar, Nadar Bagh, Tehsil Sadar Behind Greenwood School, Ekta Vihar Colo, Ny, Rampur, Rampur, Uttar Pradesh UP, Rampur, Nadar Bagh, Tehsil Sadar Behind Greenwood School, Ekta Vihar Colo, Ny, Rampur, Madyan Nagar
             Garcia Mountain Biotherapeutics PLLC            Garcia Mountain Biootherapeutics PLLC     0.986301        0.986301                                                                                  11171 Samish Island Road, Bow, WA                                                                    SAMISH ISLAND RD, null, BOW  CDP, WA
            Carrico, Inge and Yamasaki Associates           Carrico, Inge and Yamdasaki Associates     0.986301        0.986301                                                                              612 Maxine Drive, City Of Socorro, TX                                                                       MAXINE DRIVE, CITY OF SOCORRO, TX
            Lynelle Wyatt Pioneer Intelligent Inc            LYNELLE WYTT PIONEER INTELLIGENT  INC     0.986301        0.986301                                                                              10600 Sacramento Street, Portland, OR
            Electronics Vidyalaya Private Limited             Electronic Vidyalaya Private Limited     0.986301        0.986301                                                 C/O Rajesh Kumar Thakkar, Fn S 1 2Nd F Pn A 324, Jaipur, Rajasthan
            Lakshmi Innovative Developers Pvt Ltd             Lakshmi Innovative Developer-Pvt Ltd     0.986301        0.986301                               J Sector, N Line, Room No 20, Cheeta Camp, Trombay, Mumbai, Mumbai City, Maharashtra                                                                               J Sector, Mumbai City, MH
            Hyacinth Costello Prime Gladstone LLC             Hyacinth Costllo Prime-Gladstone LLC     0.986301        0.986301                                                                               405 Modesto Avenue, Russellville, AR
             Pioneer Technologies Private Limited            Pioneer Technologies Prisvate Limited     0.986301        0.986301                                                   C/O Sirajul Malik, Chaudhrana, Malihabad, Lucknow, Uttar Pradesh                                         H.NO 780 C/O SIRAJUL MALIK, CHAUDHRANA, MALIHABAD, उत्तर प्रदेश
             Physical Therapy Care Associates LLC            Physical Therapy Care Assomciates LLC     0.986301        0.986301                                                                                  590 Windswept Ridge, Marshall, NC                                                                           MARSHALL, NC, WINDSWEPT RIDGE

In [65]:
# Load the full S2 and S3 source files.
# We only keep the columns needed for candidate generation.

SOURCE_COLUMNS = [
    "entity_id",
    "business_name",
    "business_address",
    "country"
]

print("Loading full S2...")

s2_full = pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print(f"S2 loaded: {len(s2_full):,} rows")

print("\nLoading full S3...")

s3_full = pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print(f"S3 loaded: {len(s3_full):,} rows")

# Normalize names
s2_full["name_norm"] = s2_full["business_name"].apply(normalize_text)
s3_full["name_norm"] = s3_full["business_name"].apply(normalize_text)

# Core names for later blocking
s2_full["name_core"] = s2_full["name_norm"].apply(remove_legal_suffix)
s3_full["name_core"] = s3_full["name_norm"].apply(remove_legal_suffix)

print("\nFinal shapes:")
print("S2:", s2_full.shape)
print("S3:", s3_full.shape)

print("\nMissing normalized names:")
print("S2:", (s2_full["name_norm"] == "").sum())
print("S3:", (s3_full["name_norm"] == "").sum())

Loading full S2...
S2 loaded: 5,034,616 rows

Loading full S3...
S3 loaded: 5,285,603 rows

Final shapes:
S2: (5034616, 6)
S3: (5285603, 6)

Missing normalized names:
S2: 0
S3: 0

In [66]:
# Combine S2 and S3 into one candidate table

s2_index = s2_full[
    ["entity_id", "name_norm", "name_core", "country"]
].copy()

s2_index["source"] = "S2"

s3_index = s3_full[
    ["entity_id", "name_norm", "name_core", "country"]
].copy()

s3_index["source"] = "S3"

candidate_index = pd.concat(
    [s2_index, s3_index],
    ignore_index=True
)

print("Total candidate records:", f"{len(candidate_index):,}")
print("S2 records:", f"{(candidate_index['source'] == 'S2').sum():,}")
print("S3 records:", f"{(candidate_index['source'] == 'S3').sum():,}")

print("\nCandidate index shape:", candidate_index.shape)

print("\nFirst 5 rows:")
print(candidate_index.head().to_string(index=False))

Total candidate records: 10,320,219
S2 records: 5,034,616
S3 records: 5,285,603

Candidate index shape: (10320219, 5)

First 5 rows:
   entity_id                      name_norm                      name_core country source
S2-166376419 र म म र क ट ग प र इव ट ल म ट ड र म म र क ट ग प र इव ट ल म ट ड   India     S2
S2-764573417      holloway peak inc seafood      holloway peak inc seafood      US     S2
S2-639257739        आद त य प र पर ट ज एलएलप        आद त य प र पर ट ज एलएलप   India     S2
S2-163963287                     summit inc                         summit      US     S2
 S2-49942811   delta tetlecommunication inc       delta tetlecommunication      US     S2

In [67]:
# Check the country distribution in the full candidate pool

print("Candidate country distribution:")
print(
    candidate_index["country"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nSampled S1 country distribution:")
print(
    sampled_s1_records["country"]
    .value_counts(dropna=False)
    .to_string()
)

Candidate country distribution:
country
US       6186873
India    4133346

Sampled S1 country distribution:
country
US       29999
India    20001

In [68]:
# Create country-specific candidate tables

us_candidates = candidate_index[
    candidate_index["country"] == "US"
].copy()

india_candidates = candidate_index[
    candidate_index["country"] == "India"
].copy()

print("US candidates:", f"{len(us_candidates):,}")
print("India candidates:", f"{len(india_candidates):,}")

print("\nUS candidate shape:", us_candidates.shape)
print("India candidate shape:", india_candidates.shape)

US candidates: 6,186,873
India candidates: 4,133,346

US candidate shape: (6186873, 5)
India candidate shape: (4133346, 5)

In [69]:
# Prepare normalized-name lists for RapidFuzz

us_names = us_candidates["name_norm"].tolist()
india_names = india_candidates["name_norm"].tolist()

print("US names:", f"{len(us_names):,}")
print("India names:", f"{len(india_names):,}")

print("\nFirst 5 US names:")
print(us_names[:5])

print("\nFirst 5 India names:")
print(india_names[:5])

US names: 6,186,873
India names: 4,133,346

First 5 US names:
['holloway peak inc seafood', 'summit inc', 'delta tetlecommunication inc', 'lee and lawson', 'chavira platinum chimera llc']

First 5 India names:
['र म म र क ट ग प र इव ट ल म ट ड', 'आद त य प र पर ट ज एलएलप', 'shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com', 'shree infracon private ltd', 'foundation excel agency private limited']

In [10]:
from rapidfuzz import process, fuzz

# Test fuzzy candidate retrieval on 100 S1 records

TEST_S1 = sampled_s1_records.head(100).copy()

fuzzy_test_results = []

for _, row in TEST_S1.iterrows():

    s1_name = row["name_norm"]
    s1_country = row["country"]

    # Select the correct country-specific name list
    if s1_country == "US":
        choices = us_names
    else:
        choices = india_names

    # Retrieve top 10 fuzzy name candidates
    matches = process.extract(
        s1_name,
        choices,
        scorer=fuzz.WRatio,
        limit=10
    )

    for matched_name, score, index in matches:
        fuzzy_test_results.append({
            "s1_id": row["entity_id"],
            "s1_name": row["business_name"],
            "matched_name": matched_name,
            "score": score / 100,
            "candidate_index": index
        })

fuzzy_test_results = pd.DataFrame(fuzzy_test_results)

print("S1 records tested:", len(TEST_S1))
print("Fuzzy candidate rows:", len(fuzzy_test_results))

print("\nExpected:")
print("100 S1 × 10 candidates = 1,000 candidate rows")

print("\nFirst 20 results:")
print(
    fuzzy_test_results.head(20).to_string(index=False)
)

NameError: name 'sampled_s1_records' is not defined

In [11]:
from rapidfuzz import process, fuzz

# Recreate the sampled S1 table from the current objects
sampled_s1_records = sampled_s1_records if "sampled_s1_records" in globals() else None

if sampled_s1_records is None:
    print("sampled_s1_records is not currently available.")
    print("We need to recreate the 50,000 sampled S1 records.")
else:
    print("sampled_s1_records is available:", sampled_s1_records.shape)

sampled_s1_records is not currently available.
We need to recreate the 50,000 sampled S1 records.

In [16]:
# Recreate the exact 50,000 S1 sample used earlier

SAMPLE_S1 = 50000

matched_s1 = full_ground_truth[
    (full_ground_truth["s2_count"] > 0) |
    (full_ground_truth["s3_count"] > 0)
].copy()

sampled_s1 = matched_s1.sample(
    n=SAMPLE_S1,
    random_state=42
)

# Retrieve the corresponding S1 records from the full S1 source
sampled_s1_ids = set(sampled_s1["source1_entity_id"])

sampled_s1_records = s1_full[
    s1_full["entity_id"].isin(sampled_s1_ids)
].copy()

print("Sampled S1 records:", len(sampled_s1_records))
print("Expected:", SAMPLE_S1)

print("\nFirst 5 records:")
print(
    sampled_s1_records.head().to_string(index=False)
)

NameError: name 's1_full' is not defined

In [13]:
# Reload the full ground-truth mapping

full_ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False
)

full_ground_truth["s2_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S2-")
)

full_ground_truth["s3_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S3-")
)

print("Ground truth shape:", full_ground_truth.shape)
print("S1 entities:", full_ground_truth["source1_entity_id"].nunique())

print("\nTotal S2 matches:", f"{full_ground_truth['s2_count'].sum():,}")
print("Total S3 matches:", f"{full_ground_truth['s3_count'].sum():,}")

NameError: name 'pd' is not defined

In [14]:
import os
import glob
import re
import unicodedata
import pandas as pd

# Find all TSV files available in Kaggle
file_paths = {
    os.path.basename(file): file
    for file in glob.glob("/kaggle/input/**/*.tsv", recursive=True)
}

print("TSV files found:", len(file_paths))

for name, path in file_paths.items():
    print(name, "->", path)

TSV files found: 7
test_source2.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
test_source3.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
test_source1.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
train_ground_truth.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
train_source3.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
train_source2.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
train_source1.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source1.tsv

In [15]:
# Reload the full ground-truth mapping

full_ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False
)

full_ground_truth["s2_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S2-")
)

full_ground_truth["s3_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S3-")
)

print("Ground truth shape:", full_ground_truth.shape)
print(
    "Unique S1 entities:",
    full_ground_truth["source1_entity_id"].nunique()
)

print("\nTotal S2 matches:", f"{full_ground_truth['s2_count'].sum():,}")
print("Total S3 matches:", f"{full_ground_truth['s3_count'].sum():,}")

Ground truth shape: (2206821, 4)
Unique S1 entities: 2206821

Total S2 matches: 3,693,619
Total S3 matches: 3,944,746

In [17]:
SAMPLE_S1 = 50000

# Keep only S1 entities that have at least one S2 or S3 match
matched_s1 = full_ground_truth[
    (full_ground_truth["s2_count"] > 0) |
    (full_ground_truth["s3_count"] > 0)
].copy()

# Recreate the exact sample used earlier
sampled_s1 = matched_s1.sample(
    n=SAMPLE_S1,
    random_state=42
)

print("Matched S1 entities available:", f"{len(matched_s1):,}")
print("Sampled S1 entities:", f"{len(sampled_s1):,}")

print("\nExpected sampled S1:", SAMPLE_S1)

print("\nFirst 5 sampled IDs:")
print(
    sampled_s1["source1_entity_id"]
    .head()
    .to_string(index=False)
)

Matched S1 entities available: 2,083,574
Sampled S1 entities: 50,000

Expected sampled S1: 50000

First 5 sampled IDs:
S1-777210964
S1-190133982
S1-970131671
S1-391999301
S1-435988542

In [19]:
# Retrieve the actual S1 records for our exact 50,000 sampled entities

sampled_s1_ids = set(sampled_s1["source1_entity_id"])

selected_s1_parts = []

for chunk in pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=200_000
):
    matched = chunk[
        chunk["entity_id"].isin(sampled_s1_ids)
    ]

    if len(matched) > 0:
        selected_s1_parts.append(matched)

sampled_s1_records = pd.concat(
    selected_s1_parts,
    ignore_index=True
)

print("Retrieved S1 records:", f"{len(sampled_s1_records):,}")
print("Expected:", f"{SAMPLE_S1:,}")

print("\nColumns:")
print(sampled_s1_records.columns.tolist())

print("\nFirst 5 records:")
print(
    sampled_s1_records.head().to_string(index=False)
)

Retrieved S1 records: 50,000
Expected: 50,000

Columns:
['entity_id', 'business_name', 'business_address', 'country']

First 5 records:
   entity_id                     business_name                                                                                        business_address country
S1-925783039               Orelee's Barbershop                                                                  1795 Westchester Drive, High Point, NC      US
S1-796227187    Foot & Ankle Allied Center LLC                                                           1216 Preston Avenue, Charlottesville City, VA      US
S1-580966525       Morbi Wires Private Limited S.No. 239/241/242, Sartanpar Road Near, Lezora Granito, At-Matel, Ta-Wanka, Ner, Morbi, Rajkot, Gujarat   India
S1-862338675          Sloan Mountain Grid Corp                                                                   3315 80th Street, City Of Kenosha, WI      US
S1-330281696 New International Private Limited                               B-148, Vikas Vihar Vikas Nagar, Uttam Nagar, New Delhi, West Delhi, Delhi   India

In [21]:
# Normalize the restored 50,000 S1 records

sampled_s1_records["name_norm"] = (
    sampled_s1_records["business_name"].apply(normalize_text)
)

sampled_s1_records["name_core"] = (
    sampled_s1_records["name_norm"].apply(remove_legal_suffix)
)

print("S1 records:", f"{len(sampled_s1_records):,}")

print("\nMissing normalized names:")
print(
    (sampled_s1_records["name_norm"] == "").sum()
)

print("\nFirst 5:")
print(
    sampled_s1_records[
        ["business_name", "name_norm", "name_core", "country"]
    ].head().to_string(index=False)
)

NameError: name 'normalize_text' is not defined

In [22]:
# Restore the normalization functions

def normalize_text(text):
    if not text:
        return ""

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Lowercase
    text = text.lower()

    # Replace punctuation with spaces
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    # Treat underscores as spaces
    text = text.replace("_", " ")

    # Collapse repeated whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


LEGAL_SUFFIXES = [
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "public limited",
    "public ltd",
    "holding company",
    "limited liability company",
    "company",
    "corporation",
    "incorporated",
    "limited",
    "llp",
    "llc",
    "corp",
    "inc",
    "pvt",
    "ltd",
    "co"
]


def remove_legal_suffix(name):
    if not name:
        return ""

    name = name.strip()

    changed = True

    while changed:
        changed = False

        for suffix in sorted(
            LEGAL_SUFFIXES,
            key=len,
            reverse=True
        ):
            pattern = rf"\s+{re.escape(suffix)}$"

            if re.search(pattern, name):
                name = re.sub(
                    pattern,
                    "",
                    name
                ).strip()

                changed = True
                break

    return name


print("Normalization functions restored successfully.")

Normalization functions restored successfully.

In [23]:
# Normalize the restored 50,000 S1 records

sampled_s1_records["name_norm"] = (
    sampled_s1_records["business_name"].apply(normalize_text)
)

sampled_s1_records["name_core"] = (
    sampled_s1_records["name_norm"].apply(remove_legal_suffix)
)

print("S1 records:", f"{len(sampled_s1_records):,}")

print("\nMissing normalized names:")
print(
    (sampled_s1_records["name_norm"] == "").sum()
)

print("\nFirst 5:")
print(
    sampled_s1_records[
        [
            "business_name",
            "name_norm",
            "name_core",
            "country"
        ]
    ].head().to_string(index=False)
)

S1 records: 50,000

Missing normalized names:
0

First 5:
                    business_name                         name_norm                name_core country
              Orelee's Barbershop               orelee s barbershop      orelee s barbershop      US
   Foot & Ankle Allied Center LLC      foot ankle allied center llc foot ankle allied center      US
      Morbi Wires Private Limited       morbi wires private limited              morbi wires   India
         Sloan Mountain Grid Corp          sloan mountain grid corp      sloan mountain grid      US
New International Private Limited new international private limited        new international   India

In [24]:
from rapidfuzz import process, fuzz

# Test fuzzy candidate retrieval on only 100 S1 records

TEST_S1 = sampled_s1_records.head(100).copy()

fuzzy_test_results = []

for _, row in TEST_S1.iterrows():

    s1_name = row["name_norm"]
    s1_country = row["country"]

    # Search only within the matching country
    if s1_country == "US":
        choices = us_names
    else:
        choices = india_names

    # Retrieve top 10 fuzzy name candidates
    matches = process.extract(
        s1_name,
        choices,
        scorer=fuzz.WRatio,
        limit=10
    )

    for matched_name, score, index in matches:
        fuzzy_test_results.append({
            "s1_id": row["entity_id"],
            "s1_name": row["business_name"],
            "matched_name": matched_name,
            "score": score / 100,
            "candidate_index": index
        })

fuzzy_test_results = pd.DataFrame(fuzzy_test_results)

print("S1 records tested:", len(TEST_S1))
print("Fuzzy candidate rows:", len(fuzzy_test_results))

print("\nExpected:")
print("100 S1 × 10 candidates = 1,000 candidate rows")

print("\nFirst 20 results:")
print(
    fuzzy_test_results.head(20).to_string(index=False)
)

NameError: name 'us_names' is not defined

In [25]:
print("candidate_index:", "candidate_index" in globals())
print("us_candidates:", "us_candidates" in globals())
print("india_candidates:", "india_candidates" in globals())
print("us_names:", "us_names" in globals())
print("india_names:", "india_names" in globals())

candidate_index: False
us_candidates: False
india_candidates: False
us_names: False
india_names: False

In [26]:
print("s2_full:", "s2_full" in globals())
print("s3_full:", "s3_full" in globals())
print("sampled_s1_records:", "sampled_s1_records" in globals())
print("full_ground_truth:", "full_ground_truth" in globals())

s2_full: False
s3_full: False
sampled_s1_records: True
full_ground_truth: True

In [27]:
# Reload only the columns needed for fuzzy name search

SOURCE_COLUMNS = [
    "entity_id",
    "business_name",
    "country"
]

print("Loading S2...")

s2_search = pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print("S2 loaded:", f"{len(s2_search):,}")

print("\nLoading S3...")

s3_search = pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print("S3 loaded:", f"{len(s3_search):,}")

# Normalize names
s2_search["name_norm"] = (
    s2_search["business_name"].apply(normalize_text)
)

s3_search["name_norm"] = (
    s3_search["business_name"].apply(normalize_text)
)

# Build country-specific search lists directly
us_names = pd.concat([
    s2_search.loc[s2_search["country"] == "US", "name_norm"],
    s3_search.loc[s3_search["country"] == "US", "name_norm"]
], ignore_index=True).tolist()

india_names = pd.concat([
    s2_search.loc[s2_search["country"] == "India", "name_norm"],
    s3_search.loc[s3_search["country"] == "India", "name_norm"]
], ignore_index=True).tolist()

print("\nSearch lists ready:")
print("US names:", f"{len(us_names):,}")
print("India names:", f"{len(india_names):,}")

Loading S2...
S2 loaded: 5,034,616

Loading S3...
S3 loaded: 5,285,603

Search lists ready:
US names: 6,186,873
India names: 4,133,346

In [1]:
from rapidfuzz import process, fuzz

TEST_S1 = sampled_s1_records.head(100).copy()

fuzzy_test_results = []

for _, row in TEST_S1.iterrows():

    s1_name = row["name_norm"]
    s1_country = row["country"]

    if s1_country == "US":
        choices = us_names
    else:
        choices = india_names

    matches = process.extract(
        s1_name,
        choices,
        scorer=fuzz.WRatio,
        limit=10
    )

    for matched_name, score, index in matches:
        fuzzy_test_results.append({
            "s1_id": row["entity_id"],
            "s1_name": row["business_name"],
            "matched_name": matched_name,
            "score": score / 100,
            "candidate_index": index
        })

fuzzy_test_results = pd.DataFrame(fuzzy_test_results)

print("S1 records tested:", len(TEST_S1))
print("Fuzzy candidate rows:", len(fuzzy_test_results))

print("\nExpected:")
print("100 S1 × 10 candidates = 1,000 candidate rows")

print("\nFirst 20 results:")
print(
    fuzzy_test_results.head(20).to_string(index=False)
)

ModuleNotFoundError: No module named 'rapidfuzz'

In [2]:
!pip install rapidfuzz -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 32.2 MB/s eta 0:00:00a 0:00:01

In [3]:
print("pd:", "pd" in globals())
print("file_paths:", "file_paths" in globals())
print("full_ground_truth:", "full_ground_truth" in globals())
print("sampled_s1_records:", "sampled_s1_records" in globals())
print("s2_search:", "s2_search" in globals())
print("s3_search:", "s3_search" in globals())
print("us_names:", "us_names" in globals())
print("india_names:", "india_names" in globals())

pd: False
file_paths: False
full_ground_truth: False
sampled_s1_records: False
s2_search: False
s3_search: False
us_names: False
india_names: False

In [4]:
import os
import glob
import re
import unicodedata
import pandas as pd

# Find Kaggle dataset files
file_paths = {
    os.path.basename(file): file
    for file in glob.glob("/kaggle/input/**/*.tsv", recursive=True)
}

print("TSV files found:", len(file_paths))

for name, path in file_paths.items():
    print(name, "->", path)

TSV files found: 7
test_source2.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source2.tsv
test_source3.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source3.tsv
test_source1.tsv -> /kaggle/input/datasets/anushkaxd/000002/test_source1.tsv
train_ground_truth.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_ground_truth.tsv
train_source3.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source3.tsv
train_source2.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source2.tsv
train_source1.tsv -> /kaggle/input/datasets/anushkaxd/000001/train_source1.tsv

In [5]:
def normalize_text(text):
    if not text:
        return ""

    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Replace punctuation with spaces
    text = re.sub(
        r"[^\w\s]",
        " ",
        text,
        flags=re.UNICODE
    )

    text = text.replace("_", " ")
    text = re.sub(r"\s+", " ", text).strip()

    return text


LEGAL_SUFFIXES = [
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "public limited",
    "public ltd",
    "holding company",
    "limited liability company",
    "company",
    "corporation",
    "incorporated",
    "limited",
    "llp",
    "llc",
    "corp",
    "inc",
    "pvt",
    "ltd",
    "co"
]


def remove_legal_suffix(name):
    if not name:
        return ""

    name = name.strip()

    changed = True

    while changed:
        changed = False

        for suffix in sorted(
            LEGAL_SUFFIXES,
            key=len,
            reverse=True
        ):
            pattern = rf"\s+{re.escape(suffix)}$"

            if re.search(pattern, name):
                name = re.sub(
                    pattern,
                    "",
                    name
                ).strip()

                changed = True
                break

    return name


print("Normalization functions restored successfully.")

Normalization functions restored successfully.

In [6]:
full_ground_truth = pd.read_csv(
    file_paths["train_ground_truth.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False
)

full_ground_truth["s2_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S2-")
)

full_ground_truth["s3_count"] = (
    full_ground_truth["matched_entity_ids"].str.count("S3-")
)

print("Ground truth shape:", full_ground_truth.shape)
print(
    "Unique S1 entities:",
    full_ground_truth["source1_entity_id"].nunique()
)

print("\nTotal S2 matches:", f"{full_ground_truth['s2_count'].sum():,}")
print("Total S3 matches:", f"{full_ground_truth['s3_count'].sum():,}")

Ground truth shape: (2206821, 4)
Unique S1 entities: 2206821

Total S2 matches: 3,693,619
Total S3 matches: 3,944,746

In [7]:
SAMPLE_S1 = 50000

matched_s1 = full_ground_truth[
    (full_ground_truth["s2_count"] > 0) |
    (full_ground_truth["s3_count"] > 0)
].copy()

sampled_s1 = matched_s1.sample(
    n=SAMPLE_S1,
    random_state=42
)

print("Matched S1 entities available:", f"{len(matched_s1):,}")
print("Sampled S1 entities:", f"{len(sampled_s1):,}")

print("\nFirst 5 sampled IDs:")
print(
    sampled_s1["source1_entity_id"]
    .head()
    .to_string(index=False)
)

Matched S1 entities available: 2,083,574
Sampled S1 entities: 50,000

First 5 sampled IDs:
S1-777210964
S1-190133982
S1-970131671
S1-391999301
S1-435988542

In [8]:
# Retrieve the actual S1 records for the exact 50,000 sampled IDs

sampled_s1_ids = set(
    sampled_s1["source1_entity_id"]
)

selected_s1_parts = []

for chunk in pd.read_csv(
    file_paths["train_source1.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    chunksize=200_000
):
    matched = chunk[
        chunk["entity_id"].isin(sampled_s1_ids)
    ]

    if len(matched) > 0:
        selected_s1_parts.append(matched)

sampled_s1_records = pd.concat(
    selected_s1_parts,
    ignore_index=True
)

print(
    "Retrieved S1 records:",
    f"{len(sampled_s1_records):,}"
)

print(
    "Expected:",
    f"{SAMPLE_S1:,}"
)

print("\nColumns:")
print(sampled_s1_records.columns.tolist())

Retrieved S1 records: 50,000
Expected: 50,000

Columns:
['entity_id', 'business_name', 'business_address', 'country']

In [9]:
# Normalize the restored S1 records

sampled_s1_records["name_norm"] = (
    sampled_s1_records["business_name"].apply(normalize_text)
)

sampled_s1_records["name_core"] = (
    sampled_s1_records["name_norm"].apply(remove_legal_suffix)
)

print("S1 records:", f"{len(sampled_s1_records):,}")

print(
    "\nMissing normalized names:",
    (sampled_s1_records["name_norm"] == "").sum()
)

print("\nFirst 5:")
print(
    sampled_s1_records[
        [
            "business_name",
            "name_norm",
            "name_core",
            "country"
        ]
    ].head().to_string(index=False)
)

S1 records: 50,000

Missing normalized names: 0

First 5:
                    business_name                         name_norm                name_core country
              Orelee's Barbershop               orelee s barbershop      orelee s barbershop      US
   Foot & Ankle Allied Center LLC      foot ankle allied center llc foot ankle allied center      US
      Morbi Wires Private Limited       morbi wires private limited              morbi wires   India
         Sloan Mountain Grid Corp          sloan mountain grid corp      sloan mountain grid      US
New International Private Limited new international private limited        new international   India

In [10]:
SOURCE_COLUMNS = [
    "entity_id",
    "business_name",
    "country"
]

print("Loading S2...")

s2_search = pd.read_csv(
    file_paths["train_source2.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print("S2 loaded:", f"{len(s2_search):,}")

print("\nLoading S3...")

s3_search = pd.read_csv(
    file_paths["train_source3.tsv"],
    sep="\t",
    dtype=str,
    keep_default_na=False,
    usecols=SOURCE_COLUMNS
)

print("S3 loaded:", f"{len(s3_search):,}")

Loading S2...
S2 loaded: 5,034,616

Loading S3...
S3 loaded: 5,285,603

In [11]:
# Normalize S2 and S3 business names

s2_search["name_norm"] = (
    s2_search["business_name"].apply(normalize_text)
)

s3_search["name_norm"] = (
    s3_search["business_name"].apply(normalize_text)
)

print("S2 empty normalized names:",
      (s2_search["name_norm"] == "").sum())

print("S3 empty normalized names:",
      (s3_search["name_norm"] == "").sum())


# Build country-specific name lists for RapidFuzz

us_names = pd.concat([
    s2_search.loc[
        s2_search["country"] == "US",
        "name_norm"
    ],
    s3_search.loc[
        s3_search["country"] == "US",
        "name_norm"
    ]
], ignore_index=True).tolist()


india_names = pd.concat([
    s2_search.loc[
        s2_search["country"] == "India",
        "name_norm"
    ],
    s3_search.loc[
        s3_search["country"] == "India",
        "name_norm"
    ]
], ignore_index=True).tolist()


print("\nUS names:", f"{len(us_names):,}")
print("India names:", f"{len(india_names):,}")

print("\nFirst 5 US names:")
print(us_names[:5])

print("\nFirst 5 India names:")
print(india_names[:5])

S2 empty normalized names: 0
S3 empty normalized names: 0

US names: 6,186,873
India names: 4,133,346

First 5 US names:
['holloway peak inc seafood', 'summit inc', 'delta tetlecommunication inc', 'lee and lawson', 'chavira platinum chimera llc']

First 5 India names:
['र म म र क ट ग प र इव ट ल म ट ड', 'आद त य प र पर ट ज एलएलप', 'shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com', 'shree infracon private ltd', 'foundation excel agency private limited']

In [14]:
from rapidfuzz import process, fuzz
import pandas as pd

# --------------------------------------------------
# TEST ONLY: start with 5 S1 records
# --------------------------------------------------

TEST_S1 = sampled_s1_records.head(5).copy()

fuzzy_test_results = []

for _, row in TEST_S1.iterrows():

    s1_name = row["name_norm"]
    s1_country = row["country"]

    # Search only within the same country
    if s1_country == "US":
        choices = us_names
    else:
        choices = india_names

    # Find top 10 fuzzy name matches
    matches = process.extract(
        s1_name,
        choices,
        scorer=fuzz.WRatio,
        limit=10
    )

    # Store the results
    for matched_name, score, index in matches:

        fuzzy_test_results.append({
            "s1_id": row["entity_id"],
            "s1_name": row["business_name"],
            "matched_name": matched_name,
            "score": score / 100,
            "candidate_index": index
        })


# Convert results to DataFrame
fuzzy_test_results = pd.DataFrame(fuzzy_test_results)


# --------------------------------------------------
# Display results
# --------------------------------------------------

print("S1 records tested:", len(TEST_S1))
print("Fuzzy candidate rows:", len(fuzzy_test_results))

print("\nExpected:")
print("5 S1 × 10 candidates = 50 candidate rows")

print("\nFuzzy matching results:")
print(
    fuzzy_test_results
    .to_string(index=False)
)

S1 records tested: 5
Fuzzy candidate rows: 50

Expected:
5 S1 × 10 candidates = 50 candidate rows

Fuzzy matching results:
       s1_id                           s1_name                      matched_name    score  candidate_index
S1-925783039               Orelee's Barbershop               orelee s barbershop 1.000000          1769142
S1-925783039               Orelee's Barbershop               orelee s barbershop 1.000000          5345373
S1-925783039               Orelee's Barbershop      orelee s barbershop downtown 0.950000           455403
S1-925783039               Orelee's Barbershop               orelee s bárbershop 0.947368          2372764
S1-925783039               Orelee's Barbershop                  lee s barbershop 0.914286          1810069
S1-925783039               Orelee's Barbershop                  lee s barbershop 0.914286          2758344
S1-925783039               Orelee's Barbershop                  lee s barbershop 0.914286          4615629
S1-925783039               Orelee's Barbershop                               lee 0.900000           915811
S1-925783039               Orelee's Barbershop                               e s 0.900000          1049525
S1-925783039               Orelee's Barbershop                             lee s 0.900000          1221961
S1-796227187    Foot & Ankle Allied Center LLC      foot ankle allied center llc 1.000000           346760
S1-796227187    Foot & Ankle Allied Center LLC             llc foot ankle center 0.950000            54401
S1-796227187    Foot & Ankle Allied Center LLC      llc foot ankle allied center 0.950000           109605
S1-796227187    Foot & Ankle Allied Center LLC             foot ankle llc center 0.950000           137643
S1-796227187    Foot & Ankle Allied Center LLC             center foot ankle llc 0.950000           148505
S1-796227187    Foot & Ankle Allied Center LLC             foot ankle llc center 0.950000           208793
S1-796227187    Foot & Ankle Allied Center LLC             foot ankle center llc 0.950000           292225
S1-796227187    Foot & Ankle Allied Center LLC             foot ankle llc center 0.950000           431775
S1-796227187    Foot & Ankle Allied Center LLC             llc foot ankle center 0.950000           465026
S1-796227187    Foot & Ankle Allied Center LLC      foot ankle center center llc 0.950000           554891
S1-580966525       Morbi Wires Private Limited               morbi wires private 0.950000            81679
S1-580966525       Morbi Wires Private Limited       morbi wires limited private 0.950000          2119938
S1-580966525       Morbi Wires Private Limited               morbi wires private 0.950000          3333533
S1-580966525       Morbi Wires Private Limited           morbi wires private ltd 0.920000          2402311
S1-580966525       Morbi Wires Private Limited           morbi wires private ltd 0.920000          2517861
S1-580966525       Morbi Wires Private Limited      morbi trades private limited 0.909091          1145761
S1-580966525       Morbi Wires Private Limited           u wires private limited 0.906818          2812489
S1-580966525       Morbi Wires Private Limited        orbit rest private limited 0.905660          1927148
S1-580966525       Morbi Wires Private Limited          morbi be private limited 0.901961           717530
S1-580966525       Morbi Wires Private Limited          gm wires private limited 0.901961          1078126
S1-862338675          Sloan Mountain Grid Corp          sloan mountain grid corp 1.000000          4987787
S1-862338675          Sloan Mountain Grid Corp            sloan mountain grid co 0.956522          6091922
S1-862338675          Sloan Mountain Grid Corp               sloan grid mountain 0.950000          1054070
S1-862338675          Sloan Mountain Grid Corp                 mountain mountain 0.950000          3129236
S1-862338675          Sloan Mountain Grid Corp                          mountain 0.900000           107004
S1-862338675          Sloan Mountain Grid Corp                          mountain 0.900000           128034
S1-862338675          Sloan Mountain Grid Corp                               loa 0.900000          1151925
S1-862338675          Sloan Mountain Grid Corp                          mountain 0.900000          1274993
S1-862338675          Sloan Mountain Grid Corp                               loa 0.900000          1342745
S1-862338675          Sloan Mountain Grid Corp                          mountain 0.900000          1488488
S1-330281696 New International Private Limited new international private limited 1.000000           100671
S1-330281696 New International Private Limited new international private limited 1.000000           368943
S1-330281696 New International Private Limited new international private limited 1.000000           484462
S1-330281696 New International Private Limited new international private limited 1.000000           552428
S1-330281696 New International Private Limited new international private limited 1.000000           715559
S1-330281696 New International Private Limited new international private limited 1.000000          1861793
S1-330281696 New International Private Limited new international private limited 1.000000          2270557
S1-330281696 New International Private Limited new international private limited 1.000000          2281455
S1-330281696 New International Private Limited new international private limited 1.000000          2524399
S1-330281696 New International Private Limited new international private limited 1.000000          2897319

In [15]:
# --------------------------------------------------
# Create entity-ID lists aligned with us_names / india_names
# --------------------------------------------------

# S2 records
s2_us = s2_search[s2_search["country"] == "US"]
s2_india = s2_search[s2_search["country"] == "India"]

# S3 records
s3_us = s3_search[s3_search["country"] == "US"]
s3_india = s3_search[s3_search["country"] == "India"]

# Entity IDs in the SAME order as the name lists
us_entity_ids = (
    s2_us["entity_id"].tolist()
    + s3_us["entity_id"].tolist()
)

india_entity_ids = (
    s2_india["entity_id"].tolist()
    + s3_india["entity_id"].tolist()
)

# --------------------------------------------------
# Verify alignment
# --------------------------------------------------

print("US names:", len(us_names))
print("US entity IDs:", len(us_entity_ids))

print("India names:", len(india_names))
print("India entity IDs:", len(india_entity_ids))

print("\nAlignment check:")

print(
    "US aligned:",
    len(us_names) == len(us_entity_ids)
)

print(
    "India aligned:",
    len(india_names) == len(india_entity_ids)
)

print("\nFirst 5 US:")
for i in range(5):
    print(us_names[i], "→", us_entity_ids[i])

print("\nFirst 5 India:")
for i in range(5):
    print(india_names[i], "→", india_entity_ids[i])

US names: 6186873
US entity IDs: 6186873
India names: 4133346
India entity IDs: 4133346

Alignment check:
US aligned: True
India aligned: True

First 5 US:
holloway peak inc seafood → S2-764573417
summit inc → S2-163963287
delta tetlecommunication inc → S2-49942811
lee and lawson → S2-138046867
chavira platinum chimera llc → S2-721031885

First 5 India:
र म म र क ट ग प र इव ट ल म ट ड → S2-166376419
आद त य प र पर ट ज एलएलप → S2-639257739
shivshakti vidyalaya vidyalaya overseas corporation www shivshakti com → S2-584977605
shree infracon private ltd → S2-277444929
foundation excel agency private limited → S2-508602797

In [20]:
# --------------------------------------------------
# Test whether fuzzy top-10 retrieves true matches
# --------------------------------------------------

test_ids = set(TEST_S1["entity_id"])

# Get ground-truth rows for these S1 entities
test_ground_truth = full_ground_truth[
    full_ground_truth["source1_entity_id"].isin(test_ids)
].copy()

# Convert matched_entity_ids into individual S2/S3 IDs
def extract_entity_ids(value):
    if not value:
        return []
    return [
        x.strip()
        for x in value.split(",")
        if x.strip()
    ]

test_ground_truth["true_entity_ids"] = (
    test_ground_truth["matched_entity_ids"]
    .apply(extract_entity_ids)
)

# --------------------------------------------------
# Add actual entity IDs to fuzzy results
# --------------------------------------------------

def get_entity_id(row):
    if row["s1_id"] not in test_ids:
        return None

    s1_country = TEST_S1.loc[
        TEST_S1["entity_id"] == row["s1_id"],
        "country"
    ].iloc[0]

    if s1_country == "US":
        return us_entity_ids[int(row["candidate_index"])]
    else:
        return india_entity_ids[int(row["candidate_index"])]


fuzzy_test_results["candidate_entity_id"] = (
    fuzzy_test_results.apply(get_entity_id, axis=1)
)

# --------------------------------------------------
# Check recall
# --------------------------------------------------

results = []

for _, gt_row in test_ground_truth.iterrows():

    s1_id = gt_row["source1_entity_id"]
    true_ids = set(gt_row["true_entity_ids"])

    candidates = set(
        fuzzy_test_results[
            fuzzy_test_results["s1_id"] == s1_id
        ]["candidate_entity_id"]
    )

    found_ids = true_ids.intersection(candidates)

    results.append({
        "s1_id": s1_id,
        "true_match_count": len(true_ids),
        "top10_candidate_count": len(candidates),
        "true_matches_found": len(found_ids),
        "all_true_matches_found": (
            len(found_ids) == len(true_ids)
        ),
        "found_entity_ids": list(found_ids)
    })

recall_test = pd.DataFrame(results)

# --------------------------------------------------
# Display
# --------------------------------------------------

print("S1 entities tested:", len(recall_test))

print(
    "\nTotal true matches:",
    recall_test["true_match_count"].sum()
)

print(
    "True matches retrieved by top-10:",
    recall_test["true_matches_found"].sum()
)

print(
    "S1 entities where ALL true matches were retrieved:",
    recall_test["all_true_matches_found"].sum(),
    "/",
    len(recall_test)
)

print("\nDetailed results:")
print(
    recall_test.to_string(index=False)
)

S1 entities tested: 5

Total true matches: 21
True matches retrieved by top-10: 12
S1 entities where ALL true matches were retrieved: 0 / 5

Detailed results:
       s1_id  true_match_count  top10_candidate_count  true_matches_found  all_true_matches_found                                                       found_entity_ids
S1-330281696                 5                     10                   2                   False                                           [S2-675464330, S2-715976968]
S1-796227187                 3                     10                   1                   False                                                         [S2-356053713]
S1-925783039                 4                     10                   3                   False                             [S2-157377754, S3-997698194, S2-517291332]
S1-862338675                 3                     10                   1                   False                                                         [S3-489874367]
S1-580966525                 6                     10                   5                   False [S3-751775609, S3-528192734, S2-987384275, S3-948190117, S3-173698306]

In [32]:
# --------------------------------------------------
# Test fuzzy top-50 recall
# --------------------------------------------------

fuzzy_top50_results = []

for _, row in TEST_S1.iterrows():

    s1_name = row["name_norm"]
    s1_country = row["country"]

    if s1_country == "US":
        choices = us_names
    else:
        choices = india_names

    matches = process.extract(
        s1_name,
        choices,
        scorer=fuzz.WRatio,
        limit=50
    )

    for matched_name, score, index in matches:

        if s1_country == "US":
            candidate_entity_id = us_entity_ids[index]
        else:
            candidate_entity_id = india_entity_ids[index]

        fuzzy_top50_results.append({
            "s1_id": row["entity_id"],
            "matched_name": matched_name,
            "score": score / 100,
            "candidate_index": index,
            "candidate_entity_id": candidate_entity_id
        })

fuzzy_top50_results = pd.DataFrame(fuzzy_top50_results)


# --------------------------------------------------
# Calculate recall
# --------------------------------------------------

results_top50 = []

for _, gt_row in test_ground_truth.iterrows():

    s1_id = gt_row["source1_entity_id"]

    true_ids = set(gt_row["true_entity_ids"])

    candidates = set(
        fuzzy_top50_results[
            fuzzy_top50_results["s1_id"] == s1_id
        ]["candidate_entity_id"]
    )

    found_ids = true_ids.intersection(candidates)

    results_top50.append({
        "s1_id": s1_id,
        "true_match_count": len(true_ids),
        "top50_candidates": len(candidates),
        "true_matches_found": len(found_ids),
        "recall": len(found_ids) / len(true_ids)
    })

recall_top50 = pd.DataFrame(results_top50)


# --------------------------------------------------
# Display
# --------------------------------------------------

print("S1 entities tested:", len(recall_top50))

print(
    "\nTotal true matches:",
    recall_top50["true_match_count"].sum()
)

print(
    "True matches retrieved by top-50:",
    recall_top50["true_matches_found"].sum()
)

print(
    "Overall recall:",
    round(
        recall_top50["true_matches_found"].sum()
        / recall_top50["true_match_count"].sum(),
        4
    )
)

print("\nDetailed results:")
print(
    recall_top50.to_string(index=False)
)

S1 entities tested: 5

Total true matches: 21
True matches retrieved by top-50: 13
Overall recall: 0.619

Detailed results:
       s1_id  true_match_count  top50_candidates  true_matches_found   recall
S1-330281696                 5                50                   3 0.600000
S1-796227187                 3                50                   1 0.333333
S1-925783039                 4                50                   3 0.750000
S1-862338675                 3                50                   1 0.333333
S1-580966525                 6                50                   5 0.833333

In [33]:
# --------------------------------------------------
# Analyze positives missed by our current blocks
# --------------------------------------------------

positive_pairs = positive_pairs_full.copy()

# Existing blocking signals
positive_pairs["name_exact"] = (
    positive_pairs["s1_name_norm"] == positive_pairs["match_name_norm"]
)

positive_pairs["core_name_exact"] = (
    positive_pairs["s1_name_core"] == positive_pairs["match_name_core"]
)


def extract_numbers(text):
    if not text:
        return set()

    return set(re.findall(r"\d+", str(text)))


positive_pairs["s1_addr_numbers"] = (
    positive_pairs["s1_address"]
    .apply(extract_numbers)
)

positive_pairs["match_addr_numbers"] = (
    positive_pairs["match_address"]
    .apply(extract_numbers)
)

positive_pairs["address_number_match"] = positive_pairs.apply(
    lambda x: bool(
        x["s1_addr_numbers"] &
        x["match_addr_numbers"]
    ),
    axis=1
)

# Combined current blocking
positive_pairs["current_block_hit"] = (
    positive_pairs["name_exact"] |
    positive_pairs["core_name_exact"] |
    positive_pairs["address_number_match"]
)

# Only the missed positives
missed = positive_pairs[
    ~positive_pairs["current_block_hit"]
].copy()

print("Total positive pairs:", len(positive_pairs))
print("Recovered by current blocks:", positive_pairs["current_block_hit"].sum())
print("Missed by current blocks:", len(missed))

print("\nMissed percentage:")
print(
    round(len(missed) / len(positive_pairs) * 100, 2),
    "%"
)

print("\nExample missed positives:")
print(
    missed[
        [
            "s1_name",
            "match_name",
            "s1_address",
            "match_address",
            "country"
        ]
    ]
    .head(20)
    .to_string(index=False)
)

NameError: name 'positive_pairs_full' is not defined